### ISSUE TITLE
[Feature Request]支持dapk

### ISSUE THREAD

**Issue by WARGBM** [UlyssesWu/FreeMote#10]
只能得到json文件，文件夹是空的。
游戏名：お兄ちゃん、キッスの準備はまだですか？ エッチの準備もまだですか？

**Comment by UlyssesWu** [comment]
1. 确保你用的是[最新编译版本](https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts)。Release中的版本较旧，仅支持Emote PSB。
2. 如果不行，把样本通过email发来。
3. dapk（我没见过）不是本项目的主要支持目标，如果你提供样本我会作调研，但不保证可解决。

**Comment by WARGBM** [comment]
@UlyssesWu dapk也是一种psb文件，里面是图片（number201724的psbfile可以编译这种文件），样本已经发谷歌邮箱。希望能添加支持。谢谢！

**Comment by UlyssesWu** [comment]
已收到。可以添加支持。请耐心等待。

**Comment by WARGBM** [comment]
@UlyssesWu 还有一种mtn格式的psb文件，不知道你是否知道？
你的工具已经可以编译这种格式，而且解出来也是png格式的图片。是否需要发一个样本给你研究，用来增加工具的稳定性？

**Comment by UlyssesWu** [comment]
其实大多数PSB变种尽管后缀名不同，但实质上据我所知都属于三类格式。本项目的工具原本是覆盖了psbfile的所有PSB功能的，但是在多次改进中渐渐地为了某些新特性break了原来的兼容性，才导致现在出现了dapk这种psbfile可兼容，本项目却不行的情况，需要修正。
既然对于mtn可以work，那么mtn想必也属于三类格式中的一种，就不需要了。等有不兼容的出现时请发给我。另外对于emote PSB即使可以兼容，只要我还没收集过，也可以发给我，我愿意收藏(/ω＼)

**Comment by UlyssesWu** [comment]
请尝试最新版本。
有问题请回复。
没问题请猛击star。
