### ISSUE TITLE
[PsbDecompile] empty folder

### ISSUE THREAD

**Issue by guranu** [UlyssesWu/FreeMote#100]
Game: Anonymous;Code
Platform: Nintendo Switch
Bug: when trying to extract in this case scenario_info.psb.m it dosen't extract anything into the folder when it supposed to
![Screenshot_20230131-211419](https://user-images.githubusercontent.com/103632948/215847503-f5b709af-faaf-4021-b7c4-fee59e3e14ed.jpg)
![Screenshot_20230131-211423](https://user-images.githubusercontent.com/103632948/215847510-b72675d8-f3b6-42b0-b213-0c9e7cbcac3f.jpg)

Here's a mega link containing the psb, the bin file and the json file: https://mega.nz/folder/dYgxlLJR#I4M6fIAIyKNar3qFiie6Tw

**Comment by UlyssesWu** [comment]
missing parameter `-l 131`.

`PsbDecompile.exe info-psb -k phV4nnwN29ppJ -l 131 scenario_info.psb.m`

**Comment by guranu** [comment]
I probably didn't type where it is located.

**Comment by guranu** [comment]
Or not because even typing the location of the psb didn't do anything.

**Comment by guranu** [comment]
also what's the paramater should be?

**Comment by UlyssesWu** [comment]
> I can't use the latest version of freemote becauss appveyor delete it.
latest release

**Comment by guranu** [comment]
> > I can't use the latest version of freemote becauss appveyor delete it.
> 
> latest release. The files on Appveyor is called "latest build" not version.

Same thing but i still can't because appveyor deletes the artifacts after a month.

**Comment by UlyssesWu** [comment]
🤔

https://github.com/UlyssesWu/FreeMote/releases/tag/v3.4.0

**Comment by guranu** [comment]
> 🤔
> 
> https://github.com/UlyssesWu/FreeMote/releases/tag/v3.4.0

I had that.

**Comment by guranu** [comment]
> > ![Screenshot_20230131-211423](https://user-images.githubusercontent.com/103632948/215847510-b72675d8-f3b6-42b0-b213-0c9e7cbcac3f.jpg)
> > Here's a mega link containing the psb, the bin file and the json file: [mega.nz/folder/dYgxlLJR#I4M6fIAIyKNar3qFiie6Tw](https://mega.nz/folder/dYgxlLJR#I4M6fIAIyKNar3qFiie6Tw)
> 
> Show me the **full** output like my screenshot. And, did you see any error dialog when run the command?

![Screenshot_20230202-112729](https://user-images.githubusercontent.com/103632948/216270472-6114fd75-b941-4732-8e34-8f48d031054c.jpg)

**Comment by UlyssesWu** [comment]
So you are running it on Win7? or even linux wine? Good luck then.

Try add argument `-1by1`. If still no luck, add `-raw` too.

**Comment by guranu** [comment]
> So you are running it on ~Win7? or even~ linux wine? Good luck then. It's normal that tools compiled for Windows may not working on other systems. Please try with a Windows PC if possible. (Or you can also try to compile/run this project using mono.)
> 
> Try add argument `-1by1`. If still no luck, add `-raw` too.

IT WORKED THANKS FOR THE HELP.

**Comment by guranu** [comment]
Ok so while it extracts most of  info psbs however when trying 
to extract the psb files from `motion` folder that are bigger than 2mb it dosen't extract them.

**Comment by UlyssesWu** [comment]
Upload files (if it's not too big, less than 200MB) and screenshots.

**Comment by guranu** [comment]
> Upload files (if it's not too big, less than 200MB) and screenshots.

![Screenshot_20230206-204438](https://user-images.githubusercontent.com/103632948/217045220-f4c43c1e-e8d1-4b78-bd3a-99b0557e30b1.jpg)
[ac_load.psb.zip](https://github.com/UlyssesWu/FreeMote/files/10667604/ac_load.psb.zip)

**Comment by guranu** [comment]
![Screenshot_20230206-204926](https://user-images.githubusercontent.com/103632948/217046418-4bbbaeaf-9d5c-4e37-96c1-74da6b58c29e.jpg)
![Screenshot_20230206-205043](https://user-images.githubusercontent.com/103632948/217046419-9d588116-d355-4799-bcef-d6b1ca0e394d.jpg)
[ac_mt_001f.psb.zip](https://github.com/UlyssesWu/FreeMote/files/10667668/ac_mt_001f.psb.zip)
[ac_mt_001s.psb.zip](https://github.com/UlyssesWu/FreeMote/files/10667669/ac_mt_001s.psb.zip)

**Comment by UlyssesWu** [comment]
All your samples can be handled with FreeMote on Windows. There is no workaround for this. You can try with `-raw`. If it works you will get `0.bin`, it's a `BC7` encoded image, use other tools (working on Wine) to decode it to png/bmp etc.
Otherwise, use a Windows computer, or try with better hardware, or ask Wine dev for a solution. 
Wine is an emulator for Windows, if some tool works on Windows but not on Wine, it's not the tool's fault, but Wine.

**Comment by guranu** [comment]
> All your samples can be handled with FreeMote on Windows. There is no workaround for this. You can try `PsbDecompile.exe ac_load.psb.m -raw`. If it works you will get `0.bin`, it's a `BC7` encoded image, use other tools (working on Wine) to decode it to png/bmp etc. Otherwise, use a Windows computer, or try with better hardware, or ask Wine dev for a solution. Wine is an emulator for Windows, if some tool works on Windows but not on Wine, it's not the tool's fault, but Wine (or maybe your hardware is poor).

Any tools you could recommend?

**Comment by UlyssesWu** [comment]
No😅 Good luck.

**Comment by guranu** [comment]
> So you are running it on ~Win7? or even~ linux wine? Good luck then. It's normal that tools compiled for Windows may not working on other systems. Please try with a Windows PC if possible. (Or you can also try to compile/run this project using mono.)
> 
> Try add argument `-1by1`. If still no luck, add `-raw` too.

How do compile it with mono?
