### ISSUE TITLE
[Question]关于Key的获取

### ISSUE THREAD

**Issue by 2652015696** [UlyssesWu/FreeMote#101]
看过部分issue，但是看了还是懵的，主要是找不到如何在dll/exe里面获取Key，基本都是发了一个Key说找到了。游戏是《Plastic Memories》移植win版。文件结构如下两图：
![Snipaste_2023-02-05_16-54-39](https://user-images.githubusercontent.com/50258919/216810414-4ae94548-40c8-48ce-a220-d87f19c001af.png)
![Snipaste_2023-02-05_16-54-09](https://user-images.githubusercontent.com/50258919/216810392-1b1c40fe-6cfb-409a-af66-c8827caf3bf6.png)
文件都是.bin和.psb.m的后缀。(两个.bak的是我替换文件留下的备份)
虽然说在dll/exe文件内寻找Key，但是我真的不知道该如何找。
这里有两个文件，一个.bin一个.psd.m。
[两个示例文件.zip](https://github.com/UlyssesWu/FreeMote/files/10610582/default.zip)
这里还有一个游戏exe文件，全部文件就只有这一个exe。
[Plastic Memories.zip](https://github.com/UlyssesWu/FreeMote/files/10610585/Plastic.Memories.zip)
(希望大佬们能教教我)
I don't know which language I should use to submit questions. If you don't understand, you can try to translate

**Comment by UlyssesWu** [comment]
`PsbDecompile.exe info-psb -k 38757621acf82 -l 131 font_info.psb.m`

最简单的方式是直接拿反汇编工具打开看。当然如果你熟悉psb.m key的套路（本wiki中略有提到），也有一些碰运气的方法，比如：
![image](https://user-images.githubusercontent.com/4312781/216812118-addd1115-e07d-49f6-bb78-d5f4ea4a511b.png)

**Comment by 2652015696** [comment]
欧！多谢大佬！但是我这里在解密时我遇到一个文件解密失败，似乎Key不一样？就是1motion_info.psb.m这个文件
![image](https://user-images.githubusercontent.com/50258919/216815031-1979900e-443c-45da-a082-7e645341350a.png)
[1motion.zip](https://github.com/UlyssesWu/FreeMote/files/10610767/1motion.zip)
(这个获取Key方法...这应该是linux里面吧，虽然我也可以重启换一个linux，如果有windows下也能操作的方法就最好了)
(反汇编的话emmmmmm....也许可能会有win版的反汇编工具？会不会用是一个问题)

**Comment by UlyssesWu** [comment]
如果你阅读了`PsbDecompile info-psb -h`，说明中有这么一句话：

> Hint: The body.bin should exist in the same folder and keep both file names correct.

https://github.com/UlyssesWu/FreeMote/wiki/PSB-Shells,-Types,-Platforms#mdfmfl-mt19937

**Comment by 2652015696** [comment]
也许是文件名正确的？
![image](https://user-images.githubusercontent.com/50258919/216815683-57e663f8-1a82-4534-932c-8f2feeb5d097.png)
至少这两个文件命名方式和其它文件是一样的
使用了EmtConvert也会提示错误
![image](https://user-images.githubusercontent.com/50258919/216815795-122b6bd2-e626-421c-87fd-1798630c8689.png)
我懵了
(原来是win的终端？我去看看)

**Comment by UlyssesWu** [comment]
只是提醒你错误的原因就是文件名不对。正确的文件名，你应该不难想到，就是`motion_info.psb.m`
后面会让PsbDecompile也支持`-s`参数。目前只能改文件名。

**Comment by 2652015696** [comment]
似乎已经能

**Comment by 2652015696** [comment]
搞定了，谢谢大佬。

**Comment by BrokenMyth** [comment]
> 欧！多谢大佬！但是我这里在解密时我遇到一个文件解密失败，似乎Key不一样？就是1motion_info.psb.m这个文件 ![image](https://user-images.githubusercontent.com/50258919/216815031-1979900e-443c-45da-a082-7e645341350a.png) [1motion.zip](https://github.com/UlyssesWu/FreeMote/files/10610767/1motion.zip) (这个获取Key方法...这应该是linux里面吧，虽然我也可以重启换一个linux，如果有windows下也能操作的方法就最好了) (反汇编的话emmmmmm....也许可能会有win版的反汇编工具？会不会用是一个问题)

good，这个秘钥可以用，拿走了，省的我去找key了🥰
