### ISSUE TITLE
[Question] Anonymous;Code Switch Green Textures

### ISSUE THREAD

**Issue by ghost** [UlyssesWu/FreeMote#102]
Game Name: Anonymous;Code Switch
PSB file samples:
[Samples.zip](https://github.com/UlyssesWu/FreeMote/files/10834572/Samples.zip)
Extracted textures:
![tex-texture](https://user-images.githubusercontent.com/126418195/221432932-9ca7d2d5-7edc-41e8-bce0-57f4924c98d4.png)
![tex000](https://user-images.githubusercontent.com/126418195/221432949-463ff33e-9610-41e3-af00-791f9f73589b.png)

Hi, I've been trying to extract the textures from Anonymous;Code for Switch but they are not extracting right. I've tried v3.4.2 and v3.3.0 an they both have the same issue. I've checked over the wiki, looked for smaller issues, and read #85. Is there an extra step I need to do to extract the texture properly?

**Comment by UlyssesWu** [comment]
v3.4.2 Works correctly on my PC. Check these:

1. Extract v3.4 tools to a new place (try not to put them on desktop or C disk) and try again.
2. Check if any dll are "blocked" by Windows (right click on `FreeMote.Plugins.dll` - Properties), or blocked or removed by your anti-virus.
3. Check if the tool output any error message. To see the error message, you should start the tool in a cmd prompt window.

**Comment by CyberForceDolls** [comment]
I did unblock those -I made sure everything was unblocked- and I tried extracting other games from the same engine. I can extract textures from other games just fine. For A;C no error is output by psbdecompile, it just output's the broken textures above.

**Comment by UlyssesWu** [comment]
I cannot come up with other ideas.
Could you upload the FreeMoteToolkit you're actually using, alongside with the FreeMote extracted files (mainly jsons)?

**Comment by CyberForceDolls** [comment]
Sorry for the delay.
[freemote.zip](https://github.com/UlyssesWu/FreeMote/files/10861766/freemote.zip)

**Comment by UlyssesWu** [comment]
I can still extract correct images with your uploaded tools. And I cannot find any bug which may cause this situation. I can only suggest you try on another computer, or debug the source code by yourself if you can.

**Comment by UlyssesWu** [comment]
Close due to user deleted. Sorry for unable to solve your problem.
