### ISSUE TITLE
Some scn files cannot be parsed(一些scn文件无法解析)

### ISSUE THREAD

**Issue by wycstc353** [UlyssesWu/FreeMote#103]
[krkr.zip](https://github.com/UlyssesWu/FreeMote/files/10920568/krkr.zip)
発情スイッチ ～美姉妹が催眠術に堕ちた先～
网盘链接：https://pan.baidu.com/s/19_4yqoNPd_3KaA2U7VUpOw
提取码：liox

秒传：
eaf084b17260ce39ba3068c050fbfda1#1289105138#hatsujosw.rar

解压码：混沌心海

**Comment by UlyssesWu** [comment]
已阅，“不可以解包”的文件中，均有一到多个字节不正确，这大概率是由于你使用的xp3解包工具有问题（推荐使用GARBro），但也可能是你的硬盘坏了。使用GARBro从xp3中提取scn后，可以正常解开。文件对比见下图。

![@$HN@()V56U9{UJ~W7WFM H](https://user-images.githubusercontent.com/4312781/223733663-f36c2809-4446-491c-9c0f-a27641e4666c.png)

**Comment by wycstc353** [comment]
> 已阅，“不可以解包”的文件中，均有一到多个字节不正确，这大概率是由于你使用的xp3解包工具有问题（推荐使用GARBro），但也可能是你的硬盘坏了。使用GARBro从xp3中提取scn后，可以正常解开。文件对比见下图。
> 
> ![@$HN@()V56U9{UJ~W7WFM H](https://user-images.githubusercontent.com/4312781/223733663-f36c2809-4446-491c-9c0f-a27641e4666c.png)

我是用XP3Viewer解的，因为别的软件封回去都会出问题

**Comment by wycstc353** [comment]
> 
然后很奇怪，这游戏用GARBro封包都不行，然后用XP3Viewer只封包scn的文件的话，就会造成游戏到a005的文件时报错，然后不改a005，快进就能进到a006，真奇怪

**Comment by UlyssesWu** [comment]
> 有这种scn的情况下，别的ks，tjs之类的改成什么编码啊，还是utf16le吗？

如果你用GARBro，你应该很容易发现该游戏的ks/tjs的编码是SHIFT-JIS。跟scn无关。

**Comment by UlyssesWu** [comment]
看不懂您的问题，与FreeMote无关的问题请您自行研究或咨询主攻Kirikiri的作者。
GARBro确实不能正确打包此游戏，您可以用自己喜欢的工具。

![image](https://user-images.githubusercontent.com/4312781/224062645-0922ec33-1b97-4ed3-88ec-c7604c3d3c62.png)

**Comment by wycstc353** [comment]
> 看不懂您的问题，与FreeMote无关的问题请您自行研究或咨询主攻Kirikiri的作者。 总结：FreeMote能够正确处理该游戏的scn文件。GARBro确实不能正确打包此游戏，您可以用自己喜欢的工具打包XP3。
> 
> ![image](https://user-images.githubusercontent.com/4312781/224062645-0922ec33-1b97-4ed3-88ec-c7604c3d3c62.png)

嗯，最后一个问题，scn是本身要求翻译内容比原文短或者和原文一样长的吗？刚测试又发现一个报错，后来发现是翻译长了

**Comment by UlyssesWu** [comment]
显然没有这种要求。但不排除某句话上挂有特殊的脚本or参数导致它无法太长。

![image](https://user-images.githubusercontent.com/4312781/224068330-8bbdc27d-546c-4ac4-8eeb-ada81c1775d8.png)

**Comment by wycstc353** [comment]
> 显然没有这种要求。但不排除某句话上挂有特殊的脚本or参数导致它无法太长。
> 
> ![image](https://user-images.githubusercontent.com/4312781/224068330-8bbdc27d-546c-4ac4-8eeb-ada81c1775d8.png)

好的，感谢大佬的帮助

**Comment by wycstc353** [comment]
> 显然没有这种要求。但不排除某句话上挂有特殊的脚本or参数导致它无法太长。
> 
> ![image](https://user-images.githubusercontent.com/4312781/224068330-8bbdc27d-546c-4ac4-8eeb-ada81c1775d8.png)

研究了好久，今天终于发现是封包软件的问题了，还是要用gar封包，gar解包时有时会根据文件名直接判断解包密匙，导致以为没有密匙
