### ISSUE TITLE
[Question] 无法用FreeMoteViewer打开mtn文件

### ISSUE THREAD

**Issue by IamnotLin** [UlyssesWu/FreeMote#105]
* Game name: Senren*banka
* Platform: PC Steam
(Because my English is really poor, I can only use Chinese, if I have to use English, please let me know.)
打扰了大佬，本来我是想着能不能通过看issues自己解决的，但我实在是个笨脑子，基本上就是完全搞不懂，所以只能求助于大佬了。
[sd001.zip](https://github.com/UlyssesWu/FreeMote/files/11122805/sd001.zip)
这是我利用GARbro从steam上面的《千恋*万花》里提取的mtn文件，它被放在data.xp3\motion\sd里。
我觉得它应该确实是motion文件，我曾经尝试用PsbDecompile打开它，然后我获得了含有图像的文件夹和两个json文件，这是其中一个json文件内的一部分信息：
![image](https://user-images.githubusercontent.com/111159978/229155365-7731e703-fb9e-4626-9932-dafa1de95439.png)
当我试着用FreeMoteViewer打开它的时候，却几乎没有反应，只能通过鼠标看见似乎有加载一秒，但是什么都没有发生，当我改成用命令行来尝试打开它的时候，我却更加一头雾水了：
![image](https://user-images.githubusercontent.com/111159978/229153166-02241fe0-cfda-4eb9-b68e-1d2faf945381.png)
如图片一般，什么都没有。
我也怀疑过是否是我安装的文件缺少了什么，所以我把文件更新到了最新版本，并尽可能确保安装了需要的组件。我还在别人的issues里下载了一个psb文件尝试打开并成功了（不过那个issues提供的文件存在一些问题，因此模型并不在正中央，不过通过移动画布我确实是看到了模型：[iro_0.zip](https://github.com/UlyssesWu/FreeMote/files/11123153/iro_0.zip)）。
我实在是不明白应该怎么做才能让FreeMoteViewer打开我获取的mtn文件，可以的话还希望大佬能帮我解惑。

**Comment by UlyssesWu** [comment]
FreeMoteViewer是用的win版本的Emote引擎，目的是预览Emote模型。
Emote模型是 motion type PSB的一种，但motion type PSB不一定是Emote模型。
你这个文件是KRKR版本的非Emote的motion type PSB。只能用KRKR版本的Emote引擎打开，win版Emote不兼容这种格式。
KRKR版本的Emote引擎只能集成在KRKR里用。

**Comment by IamnotLin** [comment]
好的，十分感谢大佬的解答

**Comment by IamnotLin** [comment]
因为我不确定我的笨脑子是否完全理解了大佬所说的，所以便再确认一下，我获取的这个文件想要打开的话只能下载KRKR，是这样的吗？

**Comment by UlyssesWu** [comment]
我不知道你想要打开这个文件的目的是什么（作为提问的技巧，这应该在你第一次提问时就表明）。

如果你是想要渲染里面的图片并且导出（这个需求太小众了，一般使用FreeMote的汉化组都不需要这么做），那目前没有任何工具可以直接做到。你可以把motion文件理解成一个类似于Adobe Flash的东西，里面可能是由多个关键帧组成的动图，**导出图片可能会有很多帧**，虽然或许你可能只需要第一帧，但万一你需要后面的第n帧，这个工具的实现难度会大很多，就好像要实现一个Flash，要计算每一帧某个元素移动到哪里、产生什么形变。如果是在此基础之上进一步封装的Emote，还涉及它的物理系统等等，更是很难直接模拟，所以还是会回到调用Emote引擎上来。

> 想要打开的话只能下载KRKR

即使你下载了，你也要学会怎么在里面调用Emote引擎，最后还要研究渲染出来怎么导出。相当于你要实现一个KRKR版的FMV，可能不算难，但要花点时间研究。这个需求有些过于小众了，如果你实现了欢迎来介绍下你是怎么做的。

**Comment by IamnotLin** [comment]
好的，再次感谢大佬的解答。

**Comment by UlyssesWu** [comment]
@IamnotLin 

Good news: Since next version (v3.5) `MtnPainter` is implemented to draw images from mtn files. Accuracy is not guaranteed.
Usage: `EmtConvert.exe paint sd001.mtn`

刚刚实现了对mtn初始状态的绘制功能。
用法：`EmtConvert.exe paint sd001.mtn`

再次提醒，mtn中存的是类似于flash的动图，这个功能对于mtn中的每个动图仅尝试输出一帧，正确性也不做保证。

Try latest build: https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts

**Comment by IamnotLin** [comment]
抱歉大佬，不知道是我的操作问题或者是什么其他原因，我输入了命令，命令行的反馈似乎也证明了它有实际工作：
![image](https://user-images.githubusercontent.com/111159978/229838081-c687b1aa-5864-46c7-9ee1-1ca51e30076d.png)
但我似乎没能找到任何输出的图片。
![image](https://user-images.githubusercontent.com/111159978/229839588-79291ed5-1c86-45ef-ac52-9fa2c5ef5884.png)

**Comment by UlyssesWu** [comment]
抱歉 是我手滑了，正确的命令是`print`而非`paint`。

**Comment by dogdie233** [comment]
@lamnotLin 我添加了一些额外的修复，你可以试试
