### ISSUE TITLE
[Question] Invalid data during PsbDecompile decoding

### ISSUE THREAD

**Issue by kirbystudy** [UlyssesWu/FreeMote#108]
Game Name: Himoutou! Umaru-Chan - Himoutou Ikusei Keikaku
Platform: PSV
![image](https://user-images.githubusercontent.com/63231787/233581042-3e24d1a4-c65b-4998-b3c1-3820a02d4fa2.png)
![image](https://user-images.githubusercontent.com/63231787/233581450-b809b5c9-d247-4d22-9d84-8cf352cb4353.png)

**Comment by UlyssesWu** [comment]
Upload files (psb.m and .bin) or read the output (`Can not find body`) and fix it by yourself.

**Comment by kirbystudy** [comment]
Your visual inspection is correct, there is no key in the game file. May I ask where to obtain the key.

**Comment by UlyssesWu** [comment]
Search "eboot" in issues or search in other forums like zenhax. I'm not a PSV pro - I don't even have a PSV.

**Comment by kirbystudy** [comment]
Thank you for your answer.

**Comment by kirbystudy** [comment]
How to obtain the key mentioned in the technical article
![image](https://user-images.githubusercontent.com/63231787/233675728-94eafd53-7511-4081-a0ba-01415271b16f.png)

**Comment by UlyssesWu** [comment]
https://github.com/UlyssesWu/FreeMote/issues/95#issuecomment-1435688851

> Search "eboot" in issues 

如果你看不懂或者不想看懂上面已经写过的英语提示，请主动使用中文交流。这里没有规定issue必须用英文（我只会将标题修改为英文）。

**Comment by kirbystudy** [comment]
![image](https://user-images.githubusercontent.com/63231787/233819736-f9f8ee37-77eb-4d94-9ecb-87fb90e0c450.png)

好的，根据上面的提示，我打开了我用Notpad++ 16进制编码 发现里面的Dump都是乱码。

**Comment by UlyssesWu** [comment]
Np++是text editor，请你换个Hex editor，看看帖子里人家用的。

**Comment by kirbystudy** [comment]
Notepad++ 我使用Hex Editor的插件，我对比了一下是差不多的
![image](https://user-images.githubusercontent.com/63231787/233824356-b9053a36-165d-4d27-8521-f26295fb85cb.png)
![image](https://user-images.githubusercontent.com/63231787/233824362-226ecba3-9c30-449a-acc6-8a1ed09a0184.png)

**Comment by UlyssesWu** [comment]
乱码是正常的，你用搜索功能在（对应文本）里面找就是了，这只能靠你自己。

**Comment by kirbystudy** [comment]
感谢，找到了，应该是这个。
![image](https://user-images.githubusercontent.com/63231787/233825279-86a26226-245f-4c31-8a36-5025fd92b298.png)

**Comment by kirbystudy** [comment]
然后根据下面的指令来吗
![image](https://user-images.githubusercontent.com/63231787/233825575-e35708a0-0bcb-434e-827f-b01fcf6190ae.png)

**Comment by kirbystudy** [comment]
感谢，成功了，可以进行下一步的操作。

**Comment by UlyssesWu** [comment]
> 然后根据下面的指令来吗

建议阅读：https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md#%E5%A5%BD%E9%97%AE%E9%A2%98%E4%B8%8E%E8%A0%A2%E9%97%AE%E9%A2%98

**Comment by kirbystudy** [comment]
抱歉抱歉，我的问题是废话。

**Comment by Peter-The-Great** [comment]
Sorry to intrude, but the key is e7231? i cant quite get the first part of the code.

(抱歉打扰您，请问密钥的剩余部分（前八个字符）+ e7231 是多少？我找不到代码的前半部分。)
