### ISSUE TITLE
PIMG <-> PSD conversion

### ISSUE THREAD

**Issue by UlyssesWu** [UlyssesWu/FreeMote#109]
@UlyssesWu any news about export pimg to psd and import psd to pimg?

_Originally posted by @imKota in https://github.com/UlyssesWu/FreeMote/issues/44#issuecomment-1567788678_

**Comment by UlyssesWu** [comment]
Usage: 
pimg to PSD:
`EmtConvert pack -s PSD xxx.pimg`
PSD to pimg:
`EmtConvert pack -s PSD xxx.pimg.PSD`

**Comment by imKota** [comment]
@UlyssesWu Files that for some reason gave an error
[bugs.zip](https://github.com/UlyssesWu/FreeMote/files/11605586/bugs.zip)

**Comment by UlyssesWu** [comment]
Fixed.

**Comment by imKota** [comment]
@UlyssesWu Thank you so much!

**Comment by UlyssesWu** [comment]
I changed it, but I have no idea what would be affected by it.

**Comment by imKota** [comment]
> I changed it, but I have no idea what would be affected by it.

The default Photoshop image settings for print are 300 DPI and 72 PPI for viewing on screen.


![image](https://github.com/UlyssesWu/FreeMote/assets/24241471/3199f093-cd09-48b0-9e2e-81869d81efe5)

Thanks:3

**Comment by UlyssesWu** [comment]
Yeah, I mean even if PPI set to 1 there is nothing bad for editing or viewing, unless you want to print it. And you can manually set the display unit to `pixel` to get correct size.

**Comment by imKota** [comment]
That's right, I was just letting you know that it's better to set the default value.

**Comment by imKota** [comment]
@UlyssesWu hello!

Could you please make the blank layers editable?
For example, when exporting to psd, save empty layers as a smart object, so that you can change the size of these layers.

In short, I have this problem now:
For example, for the tab_sdcg button the trigger area is 86*65 pixels,
![image](https://github.com/UlyssesWu/FreeMote/assets/24241471/bf97d69f-df6d-427a-ab3a-fd73606afbb3)

![image](https://github.com/UlyssesWu/FreeMote/assets/24241471/c1c00098-9daf-42e4-93f4-3c2d6d5cb24f)

The text does not fit in this size, so I decided to increase this area to 102*56 (by converting to a smart object, and changing the size of the canvas of the smart object), but export psd back to pimg does not work.

**Comment by UlyssesWu** [comment]
@imKota You just cannot use "smart object". Smart objects can be vectorized and only Photoshop can handle them. You have to use PS "Rasterize" feature to convert a smart object to a normal layer. That's a very common procedure.

And, if you're trying to add graphic to a placeholder layer (a layer with `#lyid#-1` after its name), you will have to remove `#lyid#-1` in PSD. However usually you won't and shouldn't do that.

**Comment by imKota** [comment]
@UlyssesWu I created a rectangle of the desired area and named it with the old name, everything works.
Thanks!

Also, layers can be unrasterized. For example, I have a lot of smart objects, and they are exported normally without rasterization. The same is true for rectangles and circles.

**Comment by imKota** [comment]
Hello, @UlyssesWu 
Can u please check this files?
[pimg errors.zip](https://github.com/UlyssesWu/FreeMote/files/13983762/pimg.errors.zip)

**Comment by UlyssesWu** [comment]
@imKota Your files are encrypted. Your extraction tool (like GARBro etc.) didn't decrypt them correctly (perhaps wrong key provided/selected).

**Comment by imKota** [comment]
@UlyssesWu I unpacked normally, as all files are unpacked via PsbDecompile (the ones I've attached too).
So if they were encrypted, they wouldn't unpack at all.

With those files that I attached the problem occurs in the [psd.Layers.Add(imageLayer)](https://github.com/UlyssesWu/FreeMote/blob/404556ac30a9697e5889520c6c3770cd3bfc64e3/FreeMote.Plugins/Shells/PsdShell.cs#L652) function and more precisely here https://github.com/UlyssesWu/FreeMote/blob/404556ac30a9697e5889520c6c3770cd3bfc64e3/FreeMote.Plugins/Shells/PsdShell.cs#L661.

**Comment by UlyssesWu** [comment]
@imKota It's not funny at all :(
It seems that you do have the decrypted files but you gave me the encrypted one. Anyway you should check your uploaded files before reply.
![image](https://github.com/UlyssesWu/FreeMote/assets/4312781/948e18a7-bb90-4482-b927-3ac3fc720cfc)

**Comment by imKota** [comment]
> @imKota It's not funny at all :( It seems that you do have the decrypted files but you gave me the encrypted one. Anyway you should have checked your uploaded files before reply. ![image](https://private-user-images.githubusercontent.com/4312781/298103405-948e18a7-bb90-4482-b927-3ac3fc720cfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NzgxOTcsIm5iZiI6MTcwNTY3Nzg5NywicGF0aCI6Ii80MzEyNzgxLzI5ODEwMzQwNS05NDhlMThhNy1iYjkwLTQ0ODItYjkyNy0zYWMzZmM3MjBjZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTlUMTUyNDU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjQzMGVmMmZjMGMwNmUxYzJmZjIyOWNkMmIyYjdhZjkwNGFiNGNiZGY2MjczYjIyOGI5MTZhY2JlNTk1ZjFmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZjJJLqCx79YvCgaqgUvPG5xp56azWTSGcIofx51jc2o)

Sorry, I did upload encrypted files.
Try number two. ;)
[error files.zip](https://github.com/UlyssesWu/FreeMote/files/13991062/error.files.zip)
