### ISSUE TITLE
[Question][PsbDecompile]PS3 Infinite Stratos 2 - Ignition Hearts GRAB-PNG

### ISSUE THREAD

**Issue by Manicsteiner** [UlyssesWu/FreeMote#113]
* Read [wiki](https://github.com/UlyssesWu/FreeMote/wiki)
* Provide game name and platform (PC/Android/PSP etc.)
* Provide PSB file samples
* Program output, or screenshots
游戏名：Infinite Stratos 2 - Ignition Hearts
平台：PS3
样本：
[Temp.zip](https://github.com/UlyssesWu/FreeMote/files/12617312/Temp.zip)

问题描述：此游戏中的图像被按RGBA解读，得到了错误的颜色，并且有颜色通道被放在了透明度通道。使用python脚本转换为GRAB顺序可以得到正确的图像。
```
    pixels = image.load()
    width, height = image.size
    for y in range(height):
        for x in range(width):
            r, g, b, a = pixels[x, y]
            pixels[x, y] = (g, r, a, b)
    
    return image
```
如果需要完整的image_body.bin请访问 [internet archive](https://archive.org/download/PS3_NOINTRO_JAP_2/Infinite%20Stratos%202%20-%20Ignition%20Hearts%20%28Japan%29.zip)
与该游戏同一系列的 Infinite Stratos 2 - Love and Purge PS3版 也有此问题。

**Comment by UlyssesWu** [comment]
感谢，已确认，近期修复。

**Comment by UlyssesWu** [comment]
已修复：[最新CI Build](https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts)
