### ISSUE TITLE
[Question] 这种格式应该如何打开或者转psd

### ISSUE THREAD

**Issue by alittlered** [UlyssesWu/FreeMote#115]
虽然文件头里写的是psb。
来自某高清galgame
[sample](https://mega.nz/file/3S5ViSAQ#bUupWX7oGpizUZ7SIY-uzS7RdlnTFHvOXKIt_ALqsn0)

**Comment by UlyssesWu** [comment]
游戏名发一下，不用藏着

**Comment by alittlered** [comment]
> 游戏名发一下，不用藏着

https://vndb.org/r33209
今年高清化的版本

**Comment by UlyssesWu** [comment]
这是Emote PSB，它不是PSD，也不能直接转成PSD。
如果你只想打开预览一下，可以用FreeMoteViewer。但你提取出来的PSB是加密的、贴图外置的，而FMV支持的是Windows DX格式PSB，是贴图内置的。你需要先用key把它解密（EmtConvert，如果你找不到key也可先PsbDecompile再PsBuild），再将贴图置入PSB（PsBuild link），最后拖到FMV上就可以预览了。
如果你想转换成立绘，你需要先拿到Emote的编辑器，然后将贴图内置的未加密PSB转换为工程文件（EmtMake）导入编辑器，从编辑器里一顿操作导出图片。流程请自己摸索。

**Comment by alittlered** [comment]
我只是想摆件瞎折腾，弄点差分自娱自乐，ok了，thanks。
