### ISSUE TITLE
Cannot compress with PSZ shell

### ISSUE THREAD

**Issue by BSPR0002** [UlyssesWu/FreeMote#116]
Cannot compress/pack with PSZ shell, but the old version is ok.
v3.5+ ✗
v1.9 ✓
[sample.zip](https://github.com/UlyssesWu/FreeMote/files/13570247/sample.zip)

## Pack with PsBuild
> PsBuild -p krkr ce01_s_body_3.json

18 Plugins Loaded.

Compiling ce01_s_body_3 ...
Compile ce01_s_body_3 failed.
System.ObjectDisposedException: 无法访问已关闭的流。
   在 System.IO.__Error.StreamIsClosed()
   在 System.IO.MemoryStream.set_Position(Int64 value)
   在 FreeMote.Plugins.Shells.PszShell.ToShell(Stream stream, Dictionary\`2 context)
   在 FreeMote.PsBuild.PsbCompiler.Compile(String inputJson, String inputResJson, String baseDir, Nullable\`1 version, Nullable\`1 cryptKey, Nullable\`1 spec, Boolean keepShell)
   在 FreeMote.PsBuild.PsbCompiler.CompileToFile(String inputPath, String outputPath, String inputResPath, Nullable\`1 version, Nullable\`1 cryptKey, Nullable\`1 platform, Boolean renameOutput, Boolean keepShell)
   在 FreeMote.Tools.PsBuild.Program.Compile(String s, Nullable\`1 version, Nullable\`1 key, Nullable\`1 spec, Boolean canRename, Boolean canPackShell)
Compile ce01_s_body_3 done.
Done.

> PsBuild --no-shell -p krkr ce01_s_body_3.json

18 Plugins Loaded.

Compiling ce01_s_body_3 ...
Compile ce01_s_body_3 done.
Done.

## Compress with EmtConvert
> EmtConvert pack -s psz ca01_l_body_1.pure.psb

18 Plugins Loaded.

Shell Convert failed: ca01_l_body_1.pure.psb
Done.

**Comment by UlyssesWu** [comment]
It's a bug. Thanks for report. Will fix soon.

**Comment by UlyssesWu** [comment]
Try latest build: https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts
