### ISSUE TITLE
[NX][OPUS] Throw error when comparing `Data.Index` and lack of `p16` support

### ISSUE THREAD

**Issue by huluhala** [UlyssesWu/FreeMote#117]
* Read [wiki](https://github.com/UlyssesWu/FreeMote/wiki)
* Provide game name and platform (PC/Android/PSP etc.)
* Provide PSB file samples
* Program output, or screenshots
游戏：dodonpachi daioujou/怒首领蜂大往生 ns平台
psb样本和运行结果https://mega.nz/folder/aMoRwSgD#DS6Q3T4sobRsCheFyVesqg
这里提供一个可以正常拆解的样本bgm_daioujou_title.psb以及不能拆解的文件se.psb
另一个游戏绊地狱的se.psb文件拆解没有问题，命令相同
![se文件夹没有输出](https://github.com/UlyssesWu/FreeMote/assets/43788895/e66a2fd5-225d-41b7-abf1-561e87eeaaf2)
![程序运行结果](https://github.com/UlyssesWu/FreeMote/assets/43788895/ecec18e4-64e8-4c06-8d08-5511498de47a)

**Comment by UlyssesWu** [comment]
请尝试最新的CI Build：https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts

此前即使你标记为“可以拆解”的样本，拆出来的也可能是有问题的：
1. 之前对于p16格式不支持，本次修复后支持
2. 之前双声道vag会被转成单声道wav，本次修复后支持转成双声道wav

所以你可以再检查下解出来的音频是否是全的。

**Comment by huluhala** [comment]
目前暂时没发现问题，感谢
