### ISSUE TITLE
无法完整提取出包含多个音频源的PSB内容

### ISSUE THREAD

**Issue by BSPR0002** [UlyssesWu/FreeMote#118]
无法完整提取出包含多个音频源的PSB内容（来源：ns）
仅能提取出第一个文件
样本（压缩分卷，附 NCA-NSP-XCI_TO_LayeredFS 的 .m 文件）：
[sound_body.1.zip](https://github.com/UlyssesWu/FreeMote/files/13824564/sound_body.1.zip)
[sound_body.2.zip](https://github.com/UlyssesWu/FreeMote/files/13824566/sound_body.2.zip)
[sound_body.3.zip](https://github.com/UlyssesWu/FreeMote/files/13824570/sound_body.3.zip)
[sound_body.4.zip](https://github.com/UlyssesWu/FreeMote/files/13824573/sound_body.4.zip)
[sound_body.5.zip](https://github.com/UlyssesWu/FreeMote/files/13824578/sound_body.5.zip)

**Comment by UlyssesWu** [comment]
解压不了。别分卷了，网盘分享或者邮件。

**Comment by BSPR0002** [comment]
@UlyssesWu 文件名改成 sound_body.zip.00x 应该就可以，github 有文件大小和类型限制，只能把名字改了

**Comment by UlyssesWu** [comment]
实测v3.7及CI Build都可以正常解出所有opus文件。

`.\PsbDecompile info-psb -k 38757621acf82 sound_info.psb.m -a`

https://github.com/UlyssesWu/FreeMote/wiki/CommandLine-Usage-for-Tools#info-psb

**Comment by BSPR0002** [comment]
抱歉，没接触过这种形式的，可否请教一下 key 是如何获得的？

**Comment by UlyssesWu** [comment]
https://github.com/UlyssesWu/FreeMote/issues/93

**Comment by BSPR0002** [comment]
感谢
