### ISSUE TITLE
[Question]FreeMote can't read this PSZ file?

### ISSUE THREAD

**Issue by mymzc4njm** [UlyssesWu/FreeMote#120]
* Read [wiki](https://github.com/UlyssesWu/FreeMote/wiki)
* Provide game name and platform (PC/Android/PSP etc.)
* Provide PSB file samples
* Program output, or screenshots

Game: アンラベル・トリガー 体験版(Trial)
[https://archive.nexton-net.jp/]

(Sorry for my bad English.)
Hello, UlyssesWu.

I did extract and got these files.
stale01aas_tex000.png and stale01aas.psz.
I think these are E-mote files, but FreeMote can't read these.

Do you have any advice?
[stale01aas.zip](https://github.com/UlyssesWu/FreeMote/files/14023864/stale01aas.zip)

**Comment by UlyssesWu** [comment]
> this doesn't seem to work.

That's because it's compressed... use EmtConvert once to decompress it from PSZ to PSB.
