### ISSUE TITLE
[Question] EmtConvert not rendering PSD result correctly(?)

### ISSUE THREAD

**Issue by xxxbagxx** [UlyssesWu/FreeMote#121]
* Read [wiki](https://github.com/UlyssesWu/FreeMote/wiki)
* Provide game name and platform (PC/Android/PSP etc.)
* Provide PSB file samples
* Program output, or screenshots

Game: いつまでも息子のママじゃいられない！３～甘やかし里美母さんのあったかおっぱいに抱かれていっぱい射精したい！～

Hello UlyssesWu,

i did the following to convert a psb file to a psd file
EmtConvert.exe pack -s PSD Sato190.psb

it renders correctly when viewing it in FreeMoteViewer but after converting it to psd using EmtConvert i get the following result
![cr](https://github.com/UlyssesWu/FreeMote/assets/105524529/eb2fe076-30c7-4485-b801-c95eed32d441)

Do you know what the issue might be?
I have attached the original psb file below.
Thanks.

[cr.zip](https://github.com/UlyssesWu/FreeMote/files/14089853/cr.zip)

**Comment by UlyssesWu** [comment]
In fact, most EMT PSBs will not be rendered correctly as the wiki has stated: **not accurate and no plan to improve**. This one is just belongs to the worst case.

It's not the recommended way if you're going to export still pictures from EMT PSB.

This PSB->PSD feature only works well for pimg type PSB. For EMT PSBs, it's just a toy.

**Comment by UlyssesWu** [comment]
I've added some hints in programs to emphasize that this will not take effect as expected. And it never will unless I hit the jackpot.

People just want to get images from EMT PSB and [here](https://github.com/UlyssesWu/FreeMote/wiki/EmtMake#export-images-from-emt-psb) is the correct way to achieve this.
