### ISSUE TITLE
System.ArgumentException: System.Text.DecoderReplacementFallback: The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback

### ISSUE THREAD

**Issue by CodeEngieer** [UlyssesWu/FreeMote#122]
Drag the psb file into FreeMoteViewer.exe
![image](https://github.com/UlyssesWu/FreeMote/assets/75971727/bc648721-836e-4e45-82f3-1468bc13284d)

**Comment by CodeEngieer** [comment]
解密的文件为爱上火车LastRun，提取资源用到的软件是KrKrExtract

**Comment by UlyssesWu** [comment]
必须提供PSB文件，不然问题将直接无视。

**Comment by CodeEngieer** [comment]
[Uploading ポーレット.zip…]()已上传

**Comment by CodeEngieer** [comment]
https://pan.baidu.com/s/1wjxg3CrQWVAv-0UU4Oom1g?pwd=nnfp

**Comment by CodeEngieer** [comment]
[[Uploading ポーレット.zip…]()](https://pan.baidu.com/s/1wjxg3CrQWVAv-0UU4Oom1g?pwd=nnfp)

**Comment by UlyssesWu** [comment]
首先，首页readme已经提示，PSB文件是以“PSB”开头。而你提取到的文件在“PSB”前面还有21个其他字节，这可能是你提取工具不兼容或是原作有意在前面加了什么东西。
但是没关系，FreeMote的_DullahanLoad_功能会自动无视前面多余的字节。

然后，你的PSB是加密的v4格式，而你没有寻找密钥并使用EmtConvert解密。
但是没关系，FreeMote的_DullahanLoad_功能能够跳过加密的部分加载PSBv4。

所以你提供的3个模型文件 无需任何额外操作 都可以正常拖到FMV上打开。我这里没有问题。

![image](https://github.com/UlyssesWu/FreeMote/assets/4312781/2449745c-7a15-4989-857e-5b516d0b4b25)

**Comment by CodeEngieer** [comment]
切换到3.62版本正常打开，新版打开出现这个报错。已解决Close吧

**Comment by CodeEngieer** [comment]
切换到3.62版本正常打开，新版打开出现这个报错。已解决Close吧
![image](https://github.com/UlyssesWu/FreeMote/assets/75971727/9d5f74a2-74aa-4dbe-a87c-8b2a34a57937)
