### ISSUE TITLE
拖动.scn文件到PsbDecompile.exe报错

### ISSUE THREAD

**Issue by WQJHS** [UlyssesWu/FreeMote#123]
管理员模式运行也没用，文件夹也非中文，不明白如何解决。

log:
未经处理的异常:  System.IO.FileNotFoundException: 未能加载文件或程序集“McMaster.Extensions.CommandLineUtils, Version=3.0.0.0, Culture=neutral, PublicKeyToken=6f71cb76b82f055d”或它的某一个依赖项。系统找不到指定的文件。
   在 FreeMote.Tools.PsbDecompile.Program.Main(String[] args)

麻烦了
祝新年快乐

**Comment by UlyssesWu** [comment]
如果你是在这里下载的3.8版本，你应该会看到压缩包内有`lib`文件夹。
你**不能**删除lib文件夹，也**不能**删除.config文件，也**不能**只将exe移动到其他位置而不移动.config文件或lib文件夹。

**Comment by WQJHS** [comment]
当时使用的时候没有移动位置，但现在重装系统后可用了。

谢谢。







                       
原始邮件
                       
                     

发件人："Ulysses"< ***@***.*** &gt;;

发件时间：2024/2/14 9:09

收件人："UlyssesWu/FreeMote"< ***@***.*** &gt;;

抄送人："WQJHS"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [UlyssesWu/FreeMote] 拖动.scn文件到PsbDecompile.exe报错 (Issue #123)




 
如果你是在这里下载的3.8版本，你应该会看到压缩包内有lib文件夹。
 你不能删除lib文件夹，也不能删除.config文件，也不能只将exe移动到其他位置而不移动.config文件或lib文件夹。
