### ISSUE TITLE
How to get key to extract info.psb.m (and body.bin) for ripping Koihime Enbu Steam?

### ISSUE THREAD

**Issue by CG33144** [UlyssesWu/FreeMote#124]
A beginner at this and searched the dlls and cdxes but to no avail, desperately need some help
Game is Koihime Enbu RyoRaiRai Version 3 on Steam PC
Here're some files that I predicted might have the MDF/MFL key alongside the one of info.psb.m examples below
[files.zip](https://github.com/UlyssesWu/FreeMote/files/14393175/files.zip)

**Comment by UlyssesWu** [comment]
It locates in the .exe file. The key is `gYk,1H.6x` and the length is `97`. 
To be honest it's the first time I saw punctuations in a key. The M2 is making some useless try to make it harder.

**Comment by CG33144** [comment]
It worked flawlessly, thank you very much!
It's definitely strange to see punctuations on a seed/key and also not in 11 (131) length, no wonder why I missed it despite being in the open. 
some of the graphics files are blurry and also in psb.m tho, how do I extract them completely as well?

**Comment by UlyssesWu** [comment]
> some of the graphics files are blurry and also in psb.m tho, how do I extract them completely as well?

Blurry doesn't sound like a FreeMote bug but you can upload a PSB sample for that if you think so.
To extract all data in .psb.m and body.bin, append `-a` (extract all):
`.\PsbDecompile.exe info-psb -k gYk,1H.6x -l 97 windata_eng_info.psb.m -a`

**Comment by CG33144** [comment]
Hmm yeah, tried again and it apparently can't extract files like these even with -a append
[ED01.psb.zip](https://github.com/UlyssesWu/FreeMote/files/14393727/ED01.psb.zip)
[SFF.zip](https://github.com/UlyssesWu/FreeMote/files/14393743/SFF.zip)
![SFF](https://github.com/UlyssesWu/FreeMote/assets/161098542/8d8f0198-cea9-4c72-9f1f-2decd6fbaa06)

[KANU SFF.zip](https://github.com/UlyssesWu/FreeMote/files/14393755/KANU.SFF.zip)

**Comment by UlyssesWu** [comment]
Okay, it's not "blurry" actually, it's a new image type which is not yet supported. I guess it may take a while.

**Comment by UlyssesWu** [comment]
@CG33144 Unfortunately your uploaded files are not decryptable directly. Is it using another key?
You may have to upload the whole psb.m + body.bin (via google drive or something). 

It's weird if you did get these files via `PsbDecompile info-psb` because this command will try it's best to output PSB instead of MDF or MFL. 
But you still got MDF/MFL. If they come from psb.m + body.bin, the key is undetermined (the relative path is a part of key, but this info is lost if you only upload such file).

**Comment by CG33144** [comment]
If it helps, I recall someone apparently managed to rip em by brute force and said that the engine is really similiar to M.U.G.E.N engine. Specifically, the modified Ikemen fighting game engine.
Other than that, I dunno. Nevertheless, thanks a lot for your help in finding the key.

**Comment by UlyssesWu** [comment]
I'm going to release the next version soon. Now I'd summarize what have been done:

### SELECT/KANU/SFF/1P000.png
Unfortunately, the image files here will not be converted (decoded). Although looks incorrect, they are stored as standard PNG files without need of any conversion by FreeMote. I don't know M2's tricks on these files, but I guess I shouldn't touch PNG files for other games' compatibility. If anyone knows how to process these special PNGs, please let me know.

### CHR/BATYOU/SFF/1Ppalette.psb.m, CHR/BATYOU/SFF/1P000.psb.m
`SprBlock` PSBs are now supported. They contain images with 8bit (palette) or 32bit depth.

### CHR/BATYOU/SFF/1PBATYOU.spr.psb.m
`SprData` PSBs are now supported. They do not contain images, but describe how to form all other PSBs in the same folder to a sprite sheet.

Currently, a basic feature `SprPainter` is implemented to render each sprite in such sheet. To get them, you have to:

1. `PsbDecompile info-psb -k gYk,1H.6x -l 97 windata_info.psb.m -a` (you must re-extract it with FreeMote v3.9+; and `-a` is required)
2. `EmtConvert print CHR\BATYOU\SFF\1PBATYOU.spr.psb.m.json`

The result will be generated in `1PBATYOU` folder, looks like this:

![image](https://github.com/user-attachments/assets/33bcdbef-5f5b-4b4e-816a-e54a882d123f)

It would be better to implement this extraction in `info-psb` steps but I don't have motivation left.

### BG/stage_chouhan/image.psb.m
`ClutImg` PSBs are now supported. They contain images, each image has a palette image (**C**olor **L**ook-**U**p **T**able).
Images (correctly colored with their CLUT) will be extracted.

###  BG/stage_chouhan/bginfo.psb.m
`Chip` PSBs are now identified, but not fully supported. It seems that they're kind of like `.spr.psb.m`, describing how to form images in `stage_chouhan/image.psb.m` into a 3D stage scene. FreeMote won't go that far to build 3D stuffs.

### module/motion/gauge.psb.m
These `Motion` PSBs are already supported.
