### ISSUE TITLE
[Switch] I don't know how to get key to extract info.psb.m

### ISSUE THREAD

**Issue by Flickable** [UlyssesWu/FreeMote#125]
I don't know how to get the key to extract the info.psb.m file. Unlike the example from issue, it's a switch file without dll or exe files. So I upload the samples info.psb.m, bin and the files that I predict have the key.
[Uploading data.zip…]()

**Comment by Flickable** [comment]
[data.zip](https://github.com/UlyssesWu/FreeMote/files/14550639/data.zip)

**Comment by UlyssesWu** [comment]
Key `523aad2de7132` found in `main`.
