### ISSUE TITLE
[Question] FreeMoteViewer无法打开mtn文件

### ISSUE THREAD

**Issue by dogdie233** [UlyssesWu/FreeMote#126]
## 问题描述
当我把一个mtn文件（从`KrkrDump`解包出来的，文件前4个字节为`PSB\0`）拖入FreeMoteViewer.exe的时候，没有任何事情发生  
通过任务管理器可以发现FreeMoteViewer进程被启动了，但几秒后又寄了  
在VS中打断点调试可以发现似乎是死在了外部的emotedriver.dll里
![emotedriver.dll寄了](https://github.com/UlyssesWu/FreeMote/assets/42267840/d0a229c8-766f-4516-a4ef-25bd68bbe93b)
虽然这可能不是本项目能解决的问题了，但是想知道怎么播放这个mtn

## 附加信息
游戏：天使纷扰RE-BOOT！
[sd003.zip](https://github.com/UlyssesWu/FreeMote/files/14631126/sd003.zip)

**Comment by UlyssesWu** [comment]
参考这个问题：#105

这是motion PSB，但不是Emote PSB。motion PSB（非EMT）没有windows版player，只有提供给厂商的KRKR版，也没公开试用版。目前唯一能打开的motion PSB的工具可能是用EmtMake转换后导入Emote Editor。

你可以通过 `EmtConvert print` 命令输出里面的每个图像的第一帧内容，但它实际上类似一种动画格式，后面的帧就不会输出了。

**Comment by dogdie233** [comment]
了解了，这个格式实在是有点眼花缭乱了😂  
这方面我也不太懂  
还是谢谢你的回复了
