### ISSUE TITLE
[PsbDecompile] Dunamis 15 PS3 config_body unpack issue

### ISSUE THREAD

**Issue by Gunoshozo** [UlyssesWu/FreeMote#129]
For Dunamis 15 when extracting config_body it produces weird result for tips.psb.m file.
Using following command:
`
PsbDecompile info-psb -k 4nDSd4sa2v config_info.psb.m -l 84
`
then
`
PsbDecompile tips.psb.m
`

![image](https://github.com/UlyssesWu/FreeMote/assets/51006468/d986970c-1fdf-4218-9d83-95b79e558591)

It says that header length is longer than file itself. And here FreeMote throws an exception.
Here is the tips file in kaitai:

![image](https://github.com/UlyssesWu/FreeMote/assets/51006468/3a359f12-607c-4429-9a51-99b09774c8eb)

It seems that the same is happening on other files (also big values in "header length" bytes)
just added "-a":
![image](https://github.com/UlyssesWu/FreeMote/assets/51006468/99932213-a01c-41fe-b54f-08de3b1b6743)

[Dunamis 15 ps3 config.zip](https://github.com/UlyssesWu/FreeMote/files/15370279/Dunamis.15.ps3.config.zip)

[config contents psbs.zip](https://github.com/UlyssesWu/FreeMote/files/15370308/config.contents.psbs.zip)

**Comment by UlyssesWu** [comment]
The header length is tampered, possibly intended. I will make it supported.
