### ISSUE TITLE
How to get the key to extract the psb.m + bin files? The Quintessential Quintuplets - Five Memories Spent With You Steam Ver.

### ISSUE THREAD

**Issue by Pabl06** [UlyssesWu/FreeMote#131]
Hi, im trying to rip all the files of the game The Quintessential Quintuplets - Five Memories Spent With You to translate it to Spanish, but i don't know hot to get the key to extract the game files.
Here's the game files: https://drive.google.com/drive/folders/1B7pnOcofVBlM2C-221iivm6fv6ZCVpm4?usp=sharing
If anyone can help, it would be a great help.

**Comment by UlyssesWu** [comment]
If you searched the keyword "Quintessential", you should be able to find the key here:
https://github.com/UlyssesWu/FreeMote/issues/62#issuecomment-1594908576

**Comment by Pabl06** [comment]
Thanks.
