### ISSUE TITLE
[Question] How to get the key to extract the psb.m + bin files? B-PROJECT RYUSEI*FANTASIA Steam Ver.

### ISSUE THREAD

**Issue by bpro-fan** [UlyssesWu/FreeMote#132]
Hello! I'd like to obtain the files from the game B-PROJECT RYUSEI*FANTASIA on PC (Steam)

I don't know how to get the key to extract the psb files. So I upload the samples font_info.psb.m, bin and the exe that I predict has the key.
[bpro_samples.zip](https://github.com/user-attachments/files/16576188/bpro_samples.zip)

Thank you very much for your help ! <3

**Comment by UlyssesWu** [comment]
key: `123abcd21asff`

**Comment by bpro-fan** [comment]
Key works, thank you very much!!!
