### ISSUE TITLE
[RVL][CI8] Castlevania: The Adventure ReBirth issues

### ISSUE THREAD

**Issue by ZoruaLoL** [UlyssesWu/FreeMote#135]
While PsbDecompile does recognize the .psb.l files and can unpack them, stuff like images come out corrupted or return an empty folder when stage data is loaded, the .json files appear to be fine however.

![logo_us-texture](https://github.com/user-attachments/assets/e9974479-f55c-4fab-810b-82dae450ba3f)
![rebirth-texture](https://github.com/user-attachments/assets/9052e7c4-2446-461b-8187-335a55bd336a)

[castlevania_rebirth_files.zip](https://github.com/user-attachments/files/16829942/castlevania_rebirth_files.zip)

**Comment by UlyssesWu** [comment]
Try latest CI build: https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts
