### ISSUE TITLE
[viewer]when I drag .psb into FreeMoteViewer.exe, nothing happen

### ISSUE THREAD

**Issue by killeromg007** [UlyssesWu/FreeMote#137]
Platfrom : PC/Win10
Psb: https://drive.google.com/file/d/19p6EUCj4ulX0cpD3PhL_9Qca7P4gbu8X/view?usp=sharing
Issue: https://drive.google.com/file/d/1xSBqiGoBoSXq7sjiTzaxpqizUfbDdUM9/view?usp=sharing

**Comment by killeromg007** [comment]
@UlyssesWu

**Comment by UlyssesWu** [comment]
duplicate of #136
