### ISSUE TITLE
[PsbDecomplie] 最新版解包出的文件名错误导致重封包后游戏无法运行

### ISSUE THREAD

**Issue by iuohua** [UlyssesWu/FreeMote#138]
使用 FreeMote v4.0 解包后，解包出的文件拓展名为 .txt.json，不对文件进行任何修改，直接使用 PsBuild 重新封包后，文件明显偏大，同时游戏在加载到该封包的内容时陷入死循环。
![image](https://github.com/user-attachments/assets/e5ef1648-e521-44d8-aa00-80e106b7bdc0)
.bak文件为源文件。

更换为 v3.7 进行解包后，解包出的文件拓展名为 .txt.scn.m.json 重新封包后文件大小比较正常，同时游戏可以正常运行。
![image](https://github.com/user-attachments/assets/44577f32-b9a7-43b8-9f58-4457ec9d3f6d)

使用 v4.0 的 PsBuild 对使用 v3.7 的 PsbDecomplie 解包出的文件进行封包，文件大小正常，游戏可以正常运行。
使用 v3.7 的 PsBuild 对使用 v4.0 的 PsbDecomplie 解包出的文件进行封包，和使用 v4.0 一样，文件大小异常，游戏无法运行。

**Comment by bGlzdGRlcg** [comment]
顺带一提，游戏为ご注文はうさぎですか?? Wonderful party!，你可以在这里下载到游戏的源文件
https://drive.google.com/file/d/1uZftDmstMKKSYju34tqih8U0ri2sboAc/view?usp=sharing(%E6%97%A0%E6%B1%89%E5%8C%96)/Gochuumon%20wa%20Usagi%20Desu%20ka%20Wonderful%20Party!.7z

**Comment by UlyssesWu** [comment]
麻烦提供样本和key。上面的链接太大了。

**Comment by bGlzdGRlcg** [comment]
[windata-bak.zip](https://github.com/user-attachments/files/17824483/windata-bak.zip)
key: 38757621acf82
