### ISSUE TITLE
[Question] How to obtain key for PlayStation 3 game '&' - Sora no Mukou de Sakimasu You ni

### ISSUE THREAD

**Issue by DSwizzy** [UlyssesWu/FreeMote#140]
I'm trying to create an uncensored 18+ patch for a PlayStation 3 Visual Novel game called '&' - Sora no Mukou de Sakimasu You ni, and i'm no way an expert on how obtain keys for console games work exactly...

Here's the image_body.bin and image_info.psb.m files i'm trying to extract: https://drive.google.com/file/d/1-P6ZztfK0yKPgFQVCKRrHpFjcjkBlXfw/view?usp=drive_link

Hopefully i'll only just need one key for the rest of the files and not need different keys for each file....

**Comment by UlyssesWu** [comment]
It's impossible to get key just from body.bin or info.psb.m files. 
Provide EBOOT.bin instead --- and I won't promise to get the key since I never played PS3, and have 0 knowledge about it.

**Comment by DSwizzy** [comment]
> It's impossible to get key just from body.bin or info.psb.m files. Provide EBOOT.bin instead --- and I won't promise to get the key since I never played PS3, and have 0 knowledge about it.

My mistake, here's the Eboot.bin file from the game: https://drive.google.com/file/d/1E49OlDbBTHVXzm1CKEZYiEcXK3jH5uwX/view?usp=sharing

**Comment by UlyssesWu** [comment]
Managed to get it (not easy for me without console experience). The key is `98dc2beff9642`. 

I didn't check the extracted content. If there're some image extraction issues, open a new issue and attach samples.
