### ISSUE TITLE
[Question] How to obtain key for PlayStation 3 game: Rui wa Tomo o Yobu

### ISSUE THREAD

**Issue by DSwizzy** [UlyssesWu/FreeMote#141]
Hey again, thank you very much for being able to grab the key for the last game you've done for me, i'd appreciate it!

Speaking of so, if your okay doing one last game for me and i'll stop the requests and also to keep from someone asking for it one day if somebody decides to do these console ports for those that don't have a PC or Android device to run 'em and prefers to play it on their PlayStation 3 instead.

Here's the Eboot.bin file for the game Rui wa Tomo o Yobu: https://drive.google.com/file/d/1xuykhs8N-7qqN5RTk4W4bmYJl8TFgdlg/view?usp=sharing

P.S. one last thing, certain script files for the game '&' - Sora no Mukou de Sakimasu You ni refused to decompile correctly when i tried getting them and these are needed for me to necessarily have the hentai scenarios/scenes to work. 

![decompile error](https://github.com/user-attachments/assets/98fc2312-7402-48a8-86e1-09e05cfd4289)

**Comment by UlyssesWu** [comment]
> P.S. one last thing, certain script files for the game '&' - Sora no Mukou de Sakimasu You ni refused to decompile correctly when i tried getting them and these are needed for me to necessarily have the hentai scenarios/scenes to work.

I didn't keep your files for last issue. I'm not sure if you have to modify these files or not.

If you just want to modify other files in "config" and keep these files untouched, you should not use `-a` like I mentioned in [another issue](https://github.com/UlyssesWu/FreeMote/issues/139#issuecomment-2495827196):

> If you won't ever edit them and you want to avoid any problem, the best choice is do not decompile and recompile them. If you are using `PsbDecompile info-psb`, you can extract PSBs without adding `-a`. Then, you just choose the PSBs you must edit, decompile and recompile and then replace them. Finally you repack with `PsBuild info-psb`. By this way you kept those map tile PSBs untouched.

If you do have to modify these files, you should also extract them without using `-a`. Then pack those extracted but cannot be deompiled files, and send to me again.

**Comment by UlyssesWu** [comment]
> Here's the Eboot.bin file for the game Rui wa Tomo o Yobu
Encrypted. I don't know what's wrong but you have provide a decrypted version just like the last time.

**Comment by DSwizzy** [comment]
> > Here's the Eboot.bin file for the game Rui wa Tomo o Yobu
> 
> Encrypted. I don't know what's wrong but you have to provide a decrypted version just like the last time.

alright, weird i didn't have to decrypt anything with the last game hmm....

**Comment by DSwizzy** [comment]
> > P.S. one last thing, certain script files for the game '&' - Sora no Mukou de Sakimasu You ni refused to decompile correctly when i tried getting them and these are needed for me to necessarily have the hentai scenarios/scenes to work.
> 
> I didn't keep your files for last issue. I'm not sure if you have to modify these files or not. The thing is, not all files are decompile-able. This "archive" type of PSBs can pack any files, not only PSBs. It's possible that these files are in other formats, like `.nut`. Perhaps you should check the file header using a hex editor. Only `PSB` or `mdf` can be decompiled.
> 
> If you just want to modify other files in "config" and keep these files untouched, you should not use `-a` like I mentioned in [another issue](https://github.com/UlyssesWu/FreeMote/issues/139#issuecomment-2495827196):
> 
> > If you won't ever edit them and you want to avoid any problem, the best choice is do not decompile and recompile them. If you are using `PsbDecompile info-psb`, you can extract PSBs without adding `-a`. Then, you just choose the PSBs you must edit, decompile and recompile and then replace them. Finally you repack with `PsBuild info-psb`. By this way you kept those map tile PSBs untouched.
> 
> If you do have to modify these files, you should also extract them without using `-a`. Then pack those extracted but cannot be deompiled files, and send to me again.

finally got around to trying that way and it finally went thru without errors now, will keep that in mind for next time and thank you very much! 👍

**Comment by UlyssesWu** [comment]
> without -a it only gives .psb.m

> I'm not sure if you have to modify these files or not.

You have to answer this question first: **Do you have to modify these files?** `psb.m` can also be repacked, too. 
If you used `-a` in `PsbDecompile`, `PsBuild` will pack all json files;
If you didn't use `-a` in `PsbDecompile`, `PsBuild` will pack all `psb.m` (and maybe other) files. And you can replace any psb.m file by extacting, modifying and repacking it.

If you do have to modify these files, I have already said, send me samples.

**Comment by UlyssesWu** [comment]
Key: `12acdd95ac539`

**Comment by DSwizzy** [comment]
> 12acdd95ac539

Thank you very much

**Comment by DSwizzy** [comment]
> > without -a it only gives .psb.m
> 
> > I'm not sure if you have to modify these files or not.
> 
> You have to answer this question first: **Do you have to modify these files?** `psb.m` can also be repacked, too. If you used `-a` in `PsbDecompile`, `PsBuild` will pack all json files; If you didn't use `-a` in `PsbDecompile`, `PsBuild` will pack all `psb.m` (and maybe other) files. And you can replace any psb.m file by extacting, modifying and repacking it.
> 
> If you do have to modify these files, I have already said, send me samples.

here's the config files for both games using the -a command as reference:

Rui wa Tomo wo Yobu: https://drive.google.com/file/d/1eFKbdZ0DMo71rfQAz66f_SaSR1GtNHS9/view?usp=sharing

'&' - Sora no Mukou de Sakimasu You ni: https://drive.google.com/file/d/1mOopORfhDeNEijM8XeuQiBsTwPV0ypsb/view?usp=sharing


And yes using that command is actually important and the only way i can modify them cuz without it, examining the .psb.m via notepad++ will give gibberish/unreadable text while with .json text output it becomes readable, so it's very likely both games ports are using extra encryption security techniques for them.

**Comment by UlyssesWu** [comment]
The lastest release (4.0.2) fixed this decompile problem.
