### ISSUE TITLE
[Question] Obtaining the key for a PS Vita game: Himouto! Umaru-chan! Himouto Ikusei Keikaku

### ISSUE THREAD

**Issue by YDGeon0510** [UlyssesWu/FreeMote#142]
Game Title: 干物妹！うまるちゃん　～干物妹！育成計画～ Himouto! Umaru-chan Himouto Ikusei Keikaku
Platform : PS Vita (2015)

Hello, I'm currently trying to extract the images and sounds from the game for an YouTube video project
and I'm not exactly sure where I should look at for the key for decrypting.

Here are some the files from the game. (including eboot.bin):
https://drive.google.com/drive/folders/14LmIRM3BdQre2hWTviOqihhFHbfB9BPc?usp=drive_link

If you need me to provide more stuff please let me know!

**Comment by UlyssesWu** [comment]
As I have said in previous issue, I'm not a sony user, and have 0 knowledge about PS consoles. 
And, to find the key is not an must solve issue for FreeMote. Currently I'm unable to get the key for PSV games.
I will try a little more when I have spare time, but if I failed or lost interest, I will close this issue.

**Comment by Manicsteiner** [comment]
PSV games are the same as Windows, open eboot.bin as text or by hex-editor, search script_info.psb.m, the key is just left before the result.

**Comment by UlyssesWu** [comment]
I don't think his eboot.bin contains such info (encrypted?) but your key is correct. That's enough. Thanks @Manicsteiner

**Comment by Manicsteiner** [comment]
> I don't think his eboot.bin contains such info (encrypted?) but your key is correct.

I didn't check that link before and just used my local files.
PSV game resource files in NoNPDRM format appear to be obfuscated in a Windows environment, and even files in common formats cannot be opened properly. If it is to extract resource files, I recommend using a maidump format game, or decrypting the PKG format file through an emulator, so that the obtained file will be normal. I haven't seen an executable file obfuscated while the resource files are normal.

**Comment by Limour-dev** [comment]
> PSV games are the same as Windows, open eboot.bin as text or by hex-editor, search script_info.psb.m, the key is just left before the result. ![图片](https://github.com/user-attachments/assets/d19405fd-e6e8-43a1-99e3-976a22bca2db)

Thank you very much! I opened the corresponding file using the `Hex Editor` in `Visual Studio Code` and searched for`script_info`. I successfully found the matching key, and then used
`PsbDecompile info-psb -k 38757621acf82 -l 131 -a scenario_info.psb.m`  to successfully unpack all the files~

非常感谢，我用 `Visual Studio Code` 的 `Hex Editor` 打开相应的文件，并搜索`script_info`，成功找到了对应的key，然后使用
`PsbDecompile info-psb -k 38757621acf82 -l 131 -a scenario_info.psb.m` 成功解包了所有的文件~

![Image](https://github.com/user-attachments/assets/a26cb05e-e648-4f88-8c89-bce5e3365e68)
