### ISSUE TITLE
[PsBuild] Changes made to resx.json file do not stick when recompiling

### ISSUE THREAD

**Issue by Levine91** [UlyssesWu/FreeMote#143]
TurboGrafx-16 Mini/PC Engine Mini/CoreGrafx Mini
I'm attempting to edit `title_us_titleselect_us.resx.json` (PSB file related) to include an additional resource, with #2 being the addition here, attempts to rebuild will be successful but not include the new resource line.

[title_us_titleselect_us.resx.json](https://github.com/user-attachments/files/18217039/title_us_titleselect_us.resx.json)
[title_us_titleselect_us.json](https://github.com/user-attachments/files/18217043/title_us_titleselect_us.json)
[title_us_titleselect_us.psb](https://github.com/user-attachments/files/18217052/title_us_titleselect_us.psb.zip)

```
{
  "PsbVersion": 4,
  "PsbType": "Motion",
  "Platform": "and",
  "CryptKey": null,
  "ExternalTextures": false,
  "Context": {},
  "Resources": {
    "0": "title_us_titleselect_us/tex#001-texture.png",
    "1": "title_us_titleselect_us/tex#000-texture.png",
    "2": "title_us_titleselect_us/tex#002-texture.png"
  }
}
```

Running through cmd directly simply shows this

![image](https://github.com/user-attachments/assets/8c059fe4-982f-4bf8-a7bd-1200ff13ae23)

**Comment by UlyssesWu** [comment]
Appearently you didn't reference `#resource#2` in `title_us_titleselect_us.json` (search for `#resource#1` and figure it out by yourself). You must actually use it if you want it be packed.

**Comment by Levine91** [comment]
Hey, no need for hostility!
That being said, doing exactly as you said worked and it's great information for the future. 
Thanks for your help and such a quick response too! Appreciate all your work.

**Comment by UlyssesWu** [comment]
@Levine91 I'm sorry if you feel bad reading my words. I mean no harm. As a open-source project without customer service, "figure it out by yourself" is always important for both impoving your skills and saving my time.
