### ISSUE TITLE
[Question]多json并有.moc3文件的疑似emote素材应该如何构建为psb？

### ISSUE THREAD

**Issue by frelixir** [UlyssesWu/FreeMote#144]
在女仆来我家s中看到fg为texture_00.xxx.png所在的model.8192文件夹，集中存放大量坐标json的motion文件夹，model.moc3文件和model.model3.json文件，似乎是某种emote解包素材，但尝试了wiki的方式无法构建成功。请问一下是否支持构建为psb？如果支持，应该如何构建为psb?
[ele_sample.zip](https://github.com/user-attachments/files/18236545/ele_sample.zip)

**Comment by UlyssesWu** [comment]
这个是`Live2D`格式。Live2D和Emote是竞品，无法互相转换。FreeMote不是为Live2D设计的工具。你可以用Live2D Viewer打开moc3文件浏览。
