### ISSUE TITLE
[PsBuild] MMO Compiler

### ISSUE THREAD

**Issue by UlyssesWu** [UlyssesWu/FreeMote#19]
A managed open-source emote project compiler, will let you create pure emote PSB (instead of just GIFs) with free editors. 

This feature is not important to me, but you are welcomed to support me to let me know you want it.

**Comment by UlyssesWu** [comment]
The official free editor is able to export some kinds of PSB, so I guess I do not need to implement this?

**Comment by leohu1** [comment]
Official free editor? Where?

**Comment by UlyssesWu** [comment]
https://emote.mtwo.co.jp/emofuri/
