### ISSUE TITLE
Unable to unpack PSB from Kami-machi Sana-chan

### ISSUE THREAD

**Issue by 0xh3LL0** [UlyssesWu/FreeMote#23]
i have tried all parameter already, but it gave me this error...

> FreeMote
>
>PSB Decompiler
by Ulysses, wdwxy12345@gmail.com
6 Plugins Loaded.
>
>Decompiling: ap_bup_yu02_02
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at FreeMote.Psb.PsbArray.get_Item(Int32 index)
   at FreeMote.Psb.PSB.LoadFromDullahan(Stream stream, Int32 detectSize)
   at FreeMote.PsBuild.PsbDecompiler.Decompile(String path, PSB& psb, Dictionary`2 context)
   at FreeMote.PsBuild.PsbDecompiler.DecompileToFile(String inputPath, PsbImageOption imageOption, PsbImageFormat extractFormat, Boolean useResx, Nullable`1 key)
   at FreeMote.Tools.PsbDecompile.Program.Decompile(String path, Boolean extractImage, Boolean uncompress, Boolean usePng, Nullable`1 key)
Done.

here some sample: [kamisana.zip](https://github.com/UlyssesWu/FreeMote/files/2948169/kamisana.zip)

**Comment by UlyssesWu** [comment]
Thanks for the samples. I can repo and locate the error and will try to fix it.

These models are _impure_ PSB, you can decompile them if you have found the key and purify them with EmtConvert, or just specify the key when using PsbDecompile. However if you don't specify the key then FreeMote will try Dullahan Load, but that is based on inference and fixed pattern so it does not always work - such as for this sample. But I will keep enhance the pattern detection method when I get new samples.

**Comment by UlyssesWu** [comment]
The latest CI build should work when using Dullahan Load (no key specified). However there are few things you can do with these models.

If you want to edit and recompile and repack them, you still need the key when compiling (Dullahan Load is a tech to load/decompile the model without key but you'll need the key when repack. The key is 0x386993A4 if you need, convert it from hex to dec).

You can get/edit textures and parameters, but you can't view those models. These models are un-common. They are all fragmentary (missing metadata) so FreeMote Viewer cannot open them. They used an uncommon EMT tech to seperate head part and body part into different PSBs, to combine a head part with different body part at runtime - that's usually a slacker idea. If you still want to view them in FMV, I will need all samples of that characters to find out if the metadata is hidden in one of them, or that's actually just a special protection.

**Comment by 0xh3LL0** [comment]
nah, i just want to extract them.
thank you very much!
