### ISSUE TITLE
Support for New Game! The Challange Stage psb files

### ISSUE THREAD

**Issue by Ristellise** [UlyssesWu/FreeMote#26]
here there. I was wondering if you could support the images files found in the game?

I managed to extract the psb files from the psb.m and .bin pairs but I'm stuck at the image format of the game.

[Samples](https://files.catbox.moe/tdadcz.zip)

**Comment by UlyssesWu** [comment]
It looks like a bitmap with pixels in special order, used only for PS4... I haven't figured out what's the order by now. 

I think morkt is better than me for this job, why not also asking him at [GARBro](https://github.com/morkt/GARbro)?

**Comment by UlyssesWu** [comment]
Good news: I've figured out how to do this. Will add support for it in 1~2 days.

**Comment by Ristellise** [comment]
Seems to work. closing issue.
