### ISSUE TITLE
[New game! The Challange Stage] Some mdf files may not be directly decompressable

### ISSUE THREAD

**Issue by Ristellise** [UlyssesWu/FreeMote#27]
This is a additional request to the previous one I made. Like the title says, New Game mdf (*.psb.m) files are obfuscated/encrypted with a crypt key.
exm2lib is able to decrypt the files by passing in a game key and a file name.
Samples will be later. but for now here is how to get the raw psb files.
Here is just the decryption of the psb.m: https://zenhax.com/viewtopic.php?t=4115#p22488

To decrypt you will need to change the `GAME_SEED`
```
set GAME_SEED binary "9362abe723sfe"
math key_len = 0x83
```
The decryption is pretty simple:
```
1. The "FileSeed" is created from the Game's Seed and the file name in full. [GameSeed + FileName]  
1b. Hash the seed with MD5. "MD5 Hash"  
2. Key is then generated using mt19937 random generator with the seed predefined as "MD5 Hash".  
3. Decrypt with Xor.  
4. And thats it. you now have the psb file.
```

[Samples](https://files.catbox.moe/jg1hhj.zip)

**Comment by UlyssesWu** [comment]
You didn't seems to show me the "game key", so I don't know how to decrypt the sample you attached.

**Comment by Ristellise** [comment]
Ah sorry! Key size is `0x81` and game key is `1232ab23478cd`

**Comment by UlyssesWu** [comment]
I think I have followed the process described in that QuickBMS script, but I still can not get the correct result. There're some things that you didn't mentioned in your steps such as MD5 hash is used. Unless you can explain this in detail, I won't think this is a feature necessary for FreeMote and you can just use exm2lib for decryption and then process the PSB with FreeMote.


![mdf](https://user-images.githubusercontent.com/4312781/57011107-9a09aa00-6c32-11e9-9aaf-440f8d125334.jpg)

**Comment by Ristellise** [comment]
Problem wirh exm2lib is that it doesnt output raw psb but all the psb files.

**Comment by UlyssesWu** [comment]
Could you explain how to XOR the file with key size (key_len) exactly? I can only decompress the decrypted mdf if I ignored the key size and xor every byte, the output has a valid PSB header but the content is incorrect. 
[config_info.psb.decompressed.zip](https://github.com/UlyssesWu/FreeMote/files/3134609/config_info.psb.decompressed.zip)

**Comment by Ristellise** [comment]
Your latter assumption is correct, ita a 128 bytes key that is cycled to every bytes in the mdf content.

**Comment by UlyssesWu** [comment]
Nope... it doesn't seems to work. The only successful attempt to decompress the mdf so far, is to ignore key size and generate a key with same size of the whole mdf (except header). However, the checksum seems to be wrong, and the output PSB is invalid (see the last sample I uploaded.)

I'm trying to push the code. You can try it via `EmtConvert mdf -k 1232ab23478cd config_info.psb.m -l 128`. If you remove `-l 128` (128 is the actual key size, I also tried 129 with no luck), you will get the same result.

**Comment by UlyssesWu** [comment]
OK, I'm over trust with your key size. It turns out that you gave me wrong key size, the correct one should be 131 (0x83).

**Comment by UlyssesWu** [comment]
You should be able to get a decompressed PSB with a valid key and key length with current version of FreeMote, that is: `EmtConvert mdf -k 1232ab23478cd config_info.psb.m -l 131`. Please have a try.

**Comment by Ristellise** [comment]
yep. the decompression works.

**Comment by Ristellise** [comment]
Update: could you maybe implement the encryption too?

**Comment by UlyssesWu** [comment]
If you'd star this project, then yes and wait for a few days.

**Comment by UlyssesWu** [comment]
The usage is same as before. FreeMote detects the input file type, and switch to pack mode if the input is a PSB.

`EmtConvert mdf -l 131 -s 1232ab23478cdconfig_info.psb.m config_info.psb.decompressed.psb`

If you don't want to keep file name right all the time, use `-s` instead of `-k` and pass a complete seed like the example does.
