### ISSUE TITLE
_info.psb.m & _body.bin

### ISSUE THREAD

**Issue by libaibaba** [UlyssesWu/FreeMote#28]
大佬你也玩崩3啊，我就想问问你这个工具，只能解_info.psb.m的吗？_body.bin的似乎不能解，我试过根据_info.psb.m解出来的psb里的json内容，在 _body.bin里找到偏移然后单独复制出来，但是EmtConvert 似乎并不认
![J674S O45S 9(}XAA 31H R](https://user-images.githubusercontent.com/52236285/60163125-80996e80-982d-11e9-8f36-6bac3822f4f2.png)
![Q%)(CH{_SDCRQXB0K~R9ION](https://user-images.githubusercontent.com/52236285/60163173-a45cb480-982d-11e9-8ec1-46e583aa5e93.png)
![B0A~)YYGJG61JK9NOOVOXXA](https://user-images.githubusercontent.com/52236285/60163199-b2aad080-982d-11e9-95c0-d652a91b9ee9.png)

exm2lib只能解不能打包，我想汉化《为美好的世界献上祝福》psv的游戏
![`~W$ W_9}VM1~2C K%J9ZB](https://user-images.githubusercontent.com/52236285/60163563-79269500-982e-11e9-826a-7d028bddbdac.png)

**Comment by UlyssesWu** [comment]
仅从图片来看，你的文件名`1.m`有问题，请把文件名改为`scenario_body.bin`，或者不使用`-k`而是使用`-s 38757621acf82`作为参数。这两者的区别我在之前的[issue](https://github.com/UlyssesWu/FreeMote/issues/27#issuecomment-488616561)中（以及EmtConvert的help里）已经讲过了。如果还不行，请上传样本，只看图永远看不出多少东西。

**Comment by libaibaba** [comment]
[新建文件夹 (4).zip](https://github.com/UlyssesWu/FreeMote/files/3329083/4.zip)

**Comment by libaibaba** [comment]
> 仅从图片来看，的你名文件`1.m`有问题，请把文件名改为`scenario_body.bin`，不或者使用`-k`而是使用`-s 38757621acf82scenario_body.bin`作为参数（也有可能是scenario_body.bin.m，反正一定要是原始的文件名）。这两者的区别我在之前的[问题](https://github.com/UlyssesWu/FreeMote/issues/27#issuecomment-488616561)中（以及EmtConvert的帮助里）已经讲过了。如果还不行，请上传样本，只看图永远看不出多少东西。

哦哦哦哦哦！！！就是命名的问题，改成EmtConvert mdf -k 38757621acf82 pr_00.txt.scn.m -l 131 就行了！大佬牛b！！！！
