### ISSUE TITLE
[Feature request] Repack *_body.bin and *_info.psb.m

### ISSUE THREAD

**Issue by 0w0NoticesBulge** [UlyssesWu/FreeMote#29]
Hi, could you add support for repacking an unpacked *_body.bin and *_info.psb.m

**Comment by UlyssesWu** [comment]
Planned, but don't have spare time for now.

**Comment by libaibaba** [comment]
If you don't feel bothered, you can do it one by one. In fact, I succeeded.

**Comment by UlyssesWu** [comment]
You can try the latest CI build. Usage:
> PsbDecompile info-psb -k {key} xxx_info.psb.m -a
> PsBuild info-psb xxx_info.psb.m.json

`-a` will decompile all files in body.bin and can be slow. If you only have to modify several files you don't need `-a`. When compiling, PsBuild will handle both decompiled jsons and undecompiled scn.m files.

For `info-psb` feature, PsBuild can only build the json exported by the latest PsbDecompile (v1.9.3+).

This feature is complicated and boring to implement so there could be many bugs.

**Comment by 0w0NoticesBulge** [comment]
Thank you very much for implementing this, it seems to work well with all the files i tried, but i'll be sure to report any bugs i encounter.
