### ISSUE TITLE
PSB 图像问题

### ISSUE THREAD

**Issue by libaibaba** [UlyssesWu/FreeMote#30]
大佬，托您的福，一切汉化进展都顺利，但是字库的图片，导出时没问题，导入后就会撕裂了，是我“PsBuild textfont24.psb.json”用法不对吗？
[textfont24.zip](https://github.com/UlyssesWu/FreeMote/files/3359228/textfont24.zip)

**Comment by UlyssesWu** [comment]
看起来像是一个bug，我会研究修复的。

**Comment by UlyssesWu** [comment]
请下载最新的CI版本测试，如无问题别忘了关闭issue。

**Comment by libaibaba** [comment]
能用了！谢谢大佬，就是黑色的描边好像变白了。。不用描边了吧，大佬如果有支付宝或者微信贴出来的话，就给大佬应援下

**Comment by UlyssesWu** [comment]
> 能用了！谢谢大佬，就是黑色的描边好像变白了。。

_“您就是列文虎克？”_ 

如果你觉得图片还是有问题，截图给我对比看看。

**Comment by libaibaba** [comment]
![J }ZC66XODGCK74HE UQL5N](https://user-images.githubusercontent.com/52236285/60678712-fc438d00-9eb7-11e9-8db3-a0f292064956.jpg)
我就是个弟弟，，，，

![GZ IN)KOL5 Z89}BK(PN0N7](https://user-images.githubusercontent.com/52236285/60678724-06658b80-9eb8-11e9-96ce-d10ea062c7dd.png)
左边的是我打包进去的，右边的是打包完出来解包的，黑色描边全白了

**Comment by libaibaba** [comment]
[新建文件夹 (5).zip](https://github.com/UlyssesWu/FreeMote/files/3359987/5.zip)
附上文件

**Comment by UlyssesWu** [comment]
你对这里面的图像格式似乎还不太了解。😪
我刚才的这个修复 #30 ，已经提示了这个PSB中的图像格式是A8，解释一下就是每个像素只占8个bit，这8个bit描述透明度（Alpha）。在这种图像里面只存在一种颜色——那就是白色，但可以有255种不同透明度的白色。你打开原本的贴图看看就知道了。

所以要解决这个问题，你要么把你图片里的黑色换成不同透明度的白色（推荐），要么把图片格式换成其他格式（新手不推荐）。不同平台上支持的图像格式有很大差异，在WIN上我们一般使用小端RGBA8也就是24位彩色+8位透明度。但是在你的目标平台（Switch）上，不一定支持RGBA8，或有可能是支持大端RGBA8。不过即使格式支持，RGBA8（32位）相比A8（8位）会导致贴图占用的内存急剧加大，可能导致游戏变卡顿，若是如此就需要采用一些更节省的图像格式。但是FreeMote主要面向PC游戏，其他平台的格式没支持几个，所以你看着办吧。

**Comment by libaibaba** [comment]
哦哦哦，谢谢大佬指点，顺带一提是psv的，5bp的游戏似乎有几个喜欢这种加密，大佬如果你未来打算支持更完美的修改*_body.bin & *_info.psb.m的话，记得密匙都不一定是一样的，密匙藏在同目录的eboot.bin的script/.script_info.psb.m前面，用十六进制软件直接搜索就行了

**Comment by UlyssesWu** [comment]
感谢讲解，但是FreeMote是处理PSB文件的工具，“自动帮你找密钥”显然不是FreeMote应有的功能。FreeMote的“输入”只应是PSB/PSB json。
就比如针对EMT PSB，如果要找PSB的密钥，那要去游戏的其他非PSB文件里找，而FreeMote已能够做到在不需要密钥的情况下解出内容（Dullahan load）或是直接推算密钥（FreeMote.Purify），这才是FreeMote期望的功能，当然这对于MT19937而言不太现实，所以你就自己提供密钥就行了。

**Comment by libaibaba** [comment]
不不不，我不是要大佬找密匙，我只是看到另一个提问里大佬说会考虑，我就怕大佬以为密匙都是一样说一下而已，exm2lib的作者就是只做了两个密匙的就鸽了，没有自定义密匙

**Comment by libaibaba** [comment]
不过0x83好像是固定的

**Comment by UlyssesWu** [comment]
如果你说的另一个提问是指 #29 ，那看来你的英语阅读理解能力也有待提高🙄。由于在CI测试服版本里我们已经支持了info.psb.m的直接解包：`PsbDecompile info-psb -k {key} {name}_info.psb.m -a`，很自然地就会有人问是否能把解包后的一堆再做打包，这是下一个会上的功能，到时你一用便知。
至于密钥是否一样，EmtConvert都支持指定密钥了，怎么会“以为密匙都是一样”？何况第一个提出类似psb的 #27 也和你给的密钥不一样啊。（但是显然同一个MDF里的子文件的密钥都是一样的。）

**Comment by libaibaba** [comment]
哦哦哦，居然已经支持了
![J }ZC66XODGCK74HE UQL5N](https://user-images.githubusercontent.com/52236285/60680737-103ebd00-9ebf-11e9-91ab-60c03f9b9297.jpg)
虽然不知道大佬你制作FreeMote的初衷是什么，但是现在已经是很强的汉化工具了，现在的再打包实际上通过十六进制的修改以及对info的修改，我已经成功换过几种字体了，也汉化了一部分进行测试
![6OR4J9H~{BPBG1XK(BN8~_6](https://user-images.githubusercontent.com/52236285/60680816-6ad81900-9ebf-11e9-814b-c7cc5b0e5a5c.jpg)
![G0NB$}UJ{)A`O`TJO`DKJX5](https://user-images.githubusercontent.com/52236285/60680821-6e6ba000-9ebf-11e9-9148-537ca3c86853.jpg)

**Comment by UlyssesWu** [comment]
FreeMote的初衷并非用于汉化，而是从命名有就暗示的`F re eMote`（详见wiki），是一套针对EMT PSB的工具（比如[这个](https://projectazusa.gitee.io/project-azusa.github.io/)）。但是由于同类PSB工具的功能较为固定，类似于你说的，连指定密钥都做不到，且操作很繁琐，要自行转换各种图像格式，所以FreeMote在两年多的开发中逐步扩展到支持各类PSB。或许其他类型的PSB你用别的工具也可以做，但对于EMT PSB做处理，FreeMote已是现在的唯一选择（笑）。

**Comment by libaibaba** [comment]
大佬牛批就对了！psbfile-master[那个](https://github.com/number201724/psbfile)我试过只有json是正常的，res里的是个奇怪的bin

**Comment by UlyssesWu** [comment]
> res里的是个奇怪的bin

“要自行转换各种图像格式”

顺便一提，FreeMote基本上还是（向下）兼容psbtools（即你说的psbfile）的，即：使用psbtools/decompiler产生的json文件，是可以由PsBuild来编译的，当然反之则不行了（PsbDecompile产生的json无法由psbtools/pcc编译）。

**Comment by libaibaba** [comment]
总之还是谢谢大佬了！早点睡吧，1点了

**Comment by UlyssesWu** [comment]
如果你愿意在汉化发布页上表示对FreeMote的赞赏，我也会非常感谢。
当然这完全是自愿的，FreeMote的License中不会有这种要求。

明天还要上班🥱

**Comment by libaibaba** [comment]
这不是肯定的吗！

**Comment by libaibaba** [comment]
大佬你喜欢爱酱头的丽塔我做出来都可以！

**Comment by UlyssesWu** [comment]
你成功吸引了我的注意力……“做出来”是啥意思
