### ISSUE TITLE
问题：如何使用原始压缩格式

### ISSUE THREAD

**Issue by liududu** [UlyssesWu/FreeMote#31]
在解包pimg格式后，自动生成了png文件，改动后封装生成了新的.pure.pimg。可是此时文件体积增大了。再对新生成文件解包,对比前后的resx.json发现context中少了"TlgVersion": 6这么一行。感觉生成时没有使用tlg压缩了，不过通过查看内部文件确实是tlg文件，感觉不压缩会对游戏有影响。求解dalao

**Comment by UlyssesWu** [comment]
文件体积增大是正常现象，绝大多数PSB使用FM（或某同类工具）打包完都会有一点点增大，因为打包的数据不可能做到100%与原来一致，这点有改进的空间，但需要花时间研究，暂时没有改进的计划，本工具不会向kiridroid党高压派妥协。

TlgVersion只是指示TLG版本用的，默认（不指定）是5，指定6则为6。不是说不指定就不转TLG的。至于少了一行，这可能是一个bug，有时间会看一下。

**Comment by liududu** [comment]
已经自行解决，需要在resx.json中修改资源的后缀名

**Comment by liududu** [comment]
感谢作者大大的解答
