### ISSUE TITLE
[EmtMake] Program output cannot be licensed by the program's creator, only the user.

### ISSUE THREAD

**Issue by baconwaifu** [UlyssesWu/FreeMote#32]
```The output file is always licensed under CC-BY-NC-SA 4.0. No commercial usage allowed!```
Is unenforcable under most copyright law, given that you are not the legal "author" of that data: 
```In general this is legally impossible; copyright law does not give you any say in the use of the output people make from their data using your program. If the user uses your program to enter or convert her own data, the copyright on the output belongs to her, not you. More generally, when a program translates its input into some other form, the copyright status of the output inherits that of the input it was generated from.``` (Source: [GPL FAQ](https://www.gnu.org/licenses/gpl-faq.en.html#GPLOutput))

You can still make a request that commercial users donate, though. (and in fact, I would encourage it, too many people take and don't give back, despite their business riding on the stuff they've "taken")

EDIT: It also conflicts with the "additional clause" at the bottom of the README saying ```If the input is not made by yourself, you are NOT allowed to use the output for any commercial purposes.``` in that it makes no distinction.

I'd advise clarifying the latter line to a notice, rather than an "additional license clause" since that's written into law anyways (and (L)GPL doesn't allow for those). something along the lines of "The output of this program inherits the license of the input. It is your responsibility to check the input file's license before distributing the output or using it commercially"

**Comment by UlyssesWu** [comment]
Thanks for pointing out this. But I do not expect anyone donates, and I do want everyone use EmtMake with NC restriction (except asking me for another license). 

I'm considering giving up the LGPL license and switching the whole project to CC BY-NC-SA.

**Comment by UlyssesWu** [comment]
I "solved" this problem by switching the whole project to CC-BY-NC-SA.

Although I'm not the author of ALL that data, the output will contain data from FreeMote (the generated file does require that injected data or it won't be able to be loaded) so it will become a "remix" of CC licensed material from FreeMote.

**Comment by UlyssesWu** [comment]
It has been a week and I assume you have been convinced by my fallacy.

There is a saying in Chinese which can be used to describe such licenses: _防君子不防小人_。
FreeMote is the only tool with these features and I've spent countless hours on it, so I wish every FreeMote user could follow the rules, to keep my passion on make it better. 🙇
