### ISSUE TITLE
build help

### ISSUE THREAD

**Issue by imKota** [UlyssesWu/FreeMote#33]
Hello, @UlyssesWu 
Can you say how to build all apps with this structure?

```
FreeMoteToolkit/EmtConvert.exe
FreeMoteToolkit/FreeMoteViewer.exe
FreeMoteToolkit/PsBuild.exe
FreeMoteToolkit/PsbDecompile.exe
FreeMoteToolkit/dll/FastBitmapLib.dll
FreeMoteToolkit/dll/FreeMote.NET.dll
FreeMoteToolkit/dll/FreeMote.Plugins.dll
FreeMoteToolkit/dll/FreeMote.PsBuild.dll
FreeMoteToolkit/dll/FreeMote.Psb.dll
FreeMoteToolkit/dll/FreeMote.dll
FreeMoteToolkit/dll/K4os.Compression.LZ4.Streams.dll
FreeMoteToolkit/dll/K4os.Compression.LZ4.dll
FreeMoteToolkit/dll/K4os.Hash.xxHash.dll
FreeMoteToolkit/dll/Newtonsoft.Json.dll
FreeMoteToolkit/dll/PhotoShop.dll
FreeMoteToolkit/dll/System.Buffers.dll
FreeMoteToolkit/dll/System.Memory.dll
FreeMoteToolkit/dll/System.Runtime.CompilerServices.Unsafe.dll
FreeMoteToolkit/dll/System.ValueTuple.dll
FreeMoteToolkit/dll/TlgLib.dll
FreeMoteToolkit/dll/XmpCore.dll
FreeMoteToolkit/dll/emotedriver.dll
```

**Comment by UlyssesWu** [comment]
I will try to fix this in next version.

**Comment by imKota** [comment]
@UlyssesWu thanks!

**Comment by imKota** [comment]
@UlyssesWu about *.scn files.
When you unpack them, empty folders are created. Do you plan to add a check so that empty folders are not created?
![image](https://user-images.githubusercontent.com/24241471/64342237-c1aebb80-cff2-11e9-9cf4-066e5a3bb55e.png)

**Comment by UlyssesWu** [comment]
Got it. Will be enhanced, too.

**Comment by UlyssesWu** [comment]
> @UlyssesWu about *.scn files.
> When you unpack them, empty folders are created. Do you plan to add a check so that empty folders are not created?

It seems that you are using some old version. This should have been fixed in v1.9.3.

**Comment by imKota** [comment]
> It seems that you are using some old version. This should have been fixed in v1.9.3.

Ohh.. sorry. In v1.9.4 fixed.

**Comment by UlyssesWu** [comment]
Fixed. Yo can try with latest CI build.

**Comment by imKota** [comment]
@UlyssesWu hello!
I try build, but..
![image](https://user-images.githubusercontent.com/24241471/64404304-26662680-d084-11e9-97c4-1945a906dfe4.png)
****

**Comment by UlyssesWu** [comment]
Yes. That file can not be moved. If you don't understand, just use [CI build](https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts) instead of compile by yourself.

**Comment by imKota** [comment]
@UlyssesWu thanks!
