### ISSUE TITLE
Plastic Memories 图像提取不正常

### ISSUE THREAD

**Issue by dewrfe53535** [UlyssesWu/FreeMote#35]
[sample.zip](https://github.com/UlyssesWu/FreeMote/files/3767304/sample.zip)
PsbDecompile解包后像素顺序完全不对......
如果用exm2lib的话只能解包出一张，大部分顺序正常的，小部分顺序乱的,有缺失的图片

**Comment by UlyssesWu** [comment]
vita是目前尚不支持的平台。会尝试做一些支持。

**Comment by UlyssesWu** [comment]
最新的build已经支持该格式，但仅限解包，暂不支持重打包（等有空再研究）。

**Comment by dewrfe53535** [comment]
这么快就搞完了，大佬NB
不过转出来的图像还需要从目前颜色的RGBA转成BGRA

**Comment by UlyssesWu** [comment]
你给的样本太少，光看这张图我还觉得颜色没什么不对甚至蛮有意境。
请给一个能明显看出应是BGRA的样本。

**Comment by dewrfe53535** [comment]
解包后的图像:[pm_ev001a.psb.m.zip](https://github.com/UlyssesWu/FreeMote/files/3771182/pm_ev001a.psb.m.zip)
官网的cg预览:http://5pb.jp/games/plastic-memories/story/img/cg1.jpg
