### ISSUE TITLE
vita CI8_SW format

### ISSUE THREAD

**Issue by woqux02** [UlyssesWu/FreeMote#36]
请问有空研究vita的打包吗？

**Comment by UlyssesWu** [comment]
可以打包啊。
93f28b2

**Comment by woqux02** [comment]
我解包motion后再打包，会有右侧这些warn，文件会变小，是使用方法有错误吗？
![img01](https://user-images.githubusercontent.com/39286465/78431501-be260480-76a7-11ea-85b3-2831906f1c19.PNG)

**Comment by UlyssesWu** [comment]
那显然是有问题的。想让我看问题在哪里，不拿出样本来肯定是不行的。

**Comment by woqux02** [comment]
好的
[样本.zip](https://github.com/UlyssesWu/FreeMote/files/4431340/default.zip)

**Comment by UlyssesWu** [comment]
……你的样本里竟然没有带上能复现你问题的“现场”（理论上你的样本应该是整个img文件夹），你也没有给出任何复现步骤，我该如何复现？我对你给的两个文件执行了Decompile和Compile操作，结果自然是没有任何问题出现。
希望您能多从对方的角度考虑考虑，如果要解决问题应该会需要什么，而不是让我来挤牙膏，浪费你我的时间。

**Comment by UlyssesWu** [comment]
Update: 我已经试出了如何复现了，你使用了-a参数。已在调查中。

**Comment by UlyssesWu** [comment]
![CI8_SW](https://user-images.githubusercontent.com/4312781/78471045-b2e2df80-7760-11ea-9934-15f61441a199.jpg)

摸清楚了。颜色应该没啥毛病吧。稍后会添加对此格式的支持。

**Comment by woqux02** [comment]
抱歉这么晚回复，以上提到的问题我会改正的。我当时试了很多参数，包括链接外部素材，奈何不懂只能找您了。感谢大佬抽时间研究，这对vita的汉化真是太有帮助了。

**Comment by UlyssesWu** [comment]
大概做好了，请从CI[下载最新build](https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts)尝试。
对CI*（调色板&索引）格式图片的支持还不能算完美，原因是为了允许修改此类图片，FreeMote会为每个图片重新生成调色板；而原始的PSB中，多个图片可能会因为用到的颜色相近/较少而共用调色板。因此FreeMote重新生成的PSB大多数情况下会比原PSB更大，对于你给的样本，会大1MB+（20919KB -> 22088KB）。后续还可以尝试做调色板合并（`FreeMote.Consts.PaletteMerge`），这个作为`nice to have`的需求，排期恐怕要很久之后了。

如果没什么问题，先留个star吧。
