### ISSUE TITLE
L8_SW image format

### ISSUE THREAD

**Issue by Ristellise** [UlyssesWu/FreeMote#37]
Samples:  

[map00.psb.m.txt](https://github.com/UlyssesWu/FreeMote/files/4489089/map00.psb.m.txt)

No need keys for this.

Key: `2shj693vwue5t`, Length: 131

[map00.psb.json.txt](https://github.com/UlyssesWu/FreeMote/files/4489092/map00.psb.json.txt)

**Comment by UlyssesWu** [comment]
L8_SW, unsupported image format for now. Will try to support it later.

**Comment by UlyssesWu** [comment]
Try the latest build.
The unswizzled image seems to have some strange pixels on top & bottom, but that seems to be the fact.
