### ISSUE TITLE
[PsBuild]Sound Archives don't compile

### ISSUE THREAD

**Issue by Cred0utofnames** [UlyssesWu/FreeMote#39]
I was trying to recompile some sound archives I had decompiled using psbdecompile with the -raw option. But I keep on getting a `[WARN](resource#) is not used.` error and the output is an empty psb archive.
I've tried this with Tokyo School Life's sound archives and Plastic Memories' sound archives.

TSL Sample:

[aoi_epaoi11_001.psb.txt](https://github.com/UlyssesWu/FreeMote/files/4526342/aoi_epaoi11_001.psb.txt)

[aoi_epaoi11_001.json.txt](https://github.com/UlyssesWu/FreeMote/files/4526343/aoi_epaoi11_001.json.txt)

PlaMemo Sample:

[pm_a01_01_eru0000.psb.txt](https://github.com/UlyssesWu/FreeMote/files/4526346/pm_a01_01_eru0000.psb.txt)

[pm_a01_01_eru0000.json.txt](https://github.com/UlyssesWu/FreeMote/files/4526347/pm_a01_01_eru0000.json.txt)

I'm also sorry for the closed issue I added a few moments before this one, I had accidentally pressed enter before writing it all down.

**Comment by UlyssesWu** [comment]
Confirmed as a bug. Will try to fix it later.

**Comment by UlyssesWu** [comment]
It should be able to compile using the latest build of PsbDecompile & PsBuild. Use the latest PsbDecompile to decompile them first.

I have no knowlegde about the resources in sound archives, the data in `pm_a01_01_eru0000` looks like a WAV but it's invalid. Could you share more info about these resources if you're trying to modify them?

**Comment by Cred0utofnames** [comment]
`pm_a01_01_eru0000` contains atrac9 data. And as for the other one, I have no idea what format it uses. The engine seems to classify any sort of sound data as "wav" files.

**Comment by UlyssesWu** [comment]
The latest [FreeMote v2.5](https://github.com/UlyssesWu/FreeMote/releases/tag/v2.5.0) can extract all samples you mentioned, and with some external tools it's also possible to repack them. 
Read [wiki](https://github.com/UlyssesWu/FreeMote/wiki/Audio) for details.
