### ISSUE TITLE
Nekopara vol. 1-3 [Nintendo Switch] (*psb.m and *.bin)

### ISSUE THREAD

**Issue by MishaIac** [UlyssesWu/FreeMote#40]
Hey. I encountered one problem when trying to unpack scenario_info.psb.m and scenario_body.bin using Freemote. I also tried using exm2lib but it didn't help either.
I think that in order to unpack these files I need to decrypt them first using the key and key size, but the problem is that I don't know where to find the key and key size for the switch version.
Maybe you can decrypt them without using the key. Or Freemote does not support switch formats at all?

[samples](https://github.com/UlyssesWu/FreeMote/files/4583078/nekopara_scenario.zip)

**Comment by UlyssesWu** [comment]
It's almost impossible to decrypt `_info.psb.m` without key. You have to find out the key. I have no knowledge about NS games so I can not help you about that. Maybe you can get some idea from https://github.com/UlyssesWu/FreeMote/issues/30#issuecomment-508534372

**Comment by MishaIac** [comment]
Well, I still managed to decrypt these files using a special exm2lib that contains the key to these files, but since I don't have the exe source code, I couldn't recognize the key.

[exm2lib (fit for all vol)](https://github.com/UlyssesWu/FreeMote/files/4585536/exm2lib_nekopara.zip)

**Comment by MishaIac** [comment]
Ahem... As strange as this sounds, I used the same key that was in #28 "38757621acf82" and it came up, size key is the same (0x83).
As a result, I was able to decrypt _info.psb.m, but _body.bin I couldn't decrypt, and exm2lib extracts files incorrectly, as you can see in the screenshot. Now, with the key, you can extract files with Freemote?
![image](https://user-images.githubusercontent.com/47920105/81170306-1dc34880-8fa3-11ea-8bb6-c8d30a420338.png)

**Comment by UlyssesWu** [comment]
`PsbDecompile.exe info-psb -k 38757621acf82 scenario_info.psb.m -l 131 -a`

However, the samples you provided has no image inside. I can't confirm if the images can be extracted correctly.

**Comment by MishaIac** [comment]
> `PsbDecompile.exe info-psb -k 38757621acf82 scenario_info.psb.m -l 131 -a`
> 
> However, the samples you provided has no image inside. I can't confirm if the images can be extracted correctly.

I extracted the images this way, but they were extracted in pieces.
![image](https://user-images.githubusercontent.com/47920105/81172596-35043500-8fa7-11ea-8ae3-50c51d794431.png)

**Comment by UlyssesWu** [comment]
This should be the fact. The CGs in PSB are just pieces. FreeMote doesn't try to combine images, and I don't think exm2lib did that.

**Comment by UlyssesWu** [comment]
If you'd upload a sample, I will evaluate whether to add such a image combine feature later.

**Comment by MishaIac** [comment]
Okay, these CGs can be glued together. What about the sound archives? I tried to extract voice_body.bin through freemote, but he couldn't.When extracted through exm2lib, thousands of .psb files appear, and when you unpack these files through freemote, they are empty.

[vol3 voice samples (GD)](https://drive.google.com/file/d/1TdonsBJ0XA9yXrZrvIgDkTgZkXvPAnqW/view?usp=sharing)

**Comment by UlyssesWu** [comment]
FreeMote has no support for extract audio to common format (wav, ogg etc.) from sound archive for now. 

It's still possible to extract the raw data by using `PsbDecompile -raw` (must use the latest build, not the v2.2 release), and it's also possible to repack it back.

**Comment by MishaIac** [comment]
> If you'd upload a sample, I will evaluate whether to add such a image combine feature later.

Of course, here's the link. [vol1 image (GD)](https://drive.google.com/file/d/1bhAlA5t_LeOP8SdcGHz4HHDGjAHVi-Oa/view?usp=sharing)

> And, it won't be hard to fix the results from exm2lib, just switch the color of each pixel (maybe R & B switch). You should try by yourself though.

I tried it that way, and it didn't work. I think that this is not the way to make the images look exactly like the original.

**Comment by UlyssesWu** [comment]
> > If you'd upload a sample, I will evaluate whether to add such a image combine feature later.
> 
> Of course, here's the link. [vol1 image (GD)](https://drive.google.com/file/d/1bhAlA5t_LeOP8SdcGHz4HHDGjAHVi-Oa/view?usp=sharing)

The sample is too large for me to download. Maybe you can just provide a single PSB in it (with pieces of images) ?

**Comment by MishaIac** [comment]
> The sample is too large for me to download. Maybe you can just provide a single PSB in it (with pieces of images) ?

[cg1cs_01a.psb.zip](https://github.com/UlyssesWu/FreeMote/files/4587909/cg1cs_01a.psb.zip)

**Comment by UlyssesWu** [comment]
Use `PsbDecompile image cg1cs_01a.psb.m` to get a combined CG image instead of pieces. The combined image will also be generated when executing `PsbDecompile cg1cs_01a.psb.m` but with pieces.

Try `EmtConvert pixel cg1cs_01a.psb+000.bmp -m ZeroTwo` (or `-m ROL` , `-m ROR` for many other situations) to fix the image from exm2lib.

There is currently no plan to support extracting common format audio files from sound archive since there is no enough infomation about the actual audio formats used in sound archive.

**Comment by UlyssesWu** [comment]
The latest [FreeMote v2.5](https://github.com/UlyssesWu/FreeMote/releases/tag/v2.5.0) can extract/repack audio from `sound_archive` you provided. 
Read [wiki](https://github.com/UlyssesWu/FreeMote/wiki/Audio) for details.

**Comment by jupmorenor** [comment]
I'm getting squared images, how to fix?
<img width="1024" height="1024" alt="Image" src="https://github.com/user-attachments/assets/3f93be6f-2f70-4faa-9c76-d94dd7bf79cd" />
