### ISSUE TITLE
[Question] ImageMetadata.SetData

### ISSUE THREAD

**Issue by marcussacana** [UlyssesWu/FreeMote#44]
I'm trying create a new ImageMetadata with this code
``` csharp
var Resource = new ImageMetadata
{
     Compress = PsbCompressType.Tlg,
     Name = $"{ID}.tlg"
};
Resource.SetData(Texture);
```
Here is where the SetData create the TLG:
https://github.com/UlyssesWu/FreeMote/blob/4760ddd4ca477292e85e94db4f9da9d43d54ef9f/FreeMote.Psb/Resources/ImageMetadata.cs#L222-L224

As you can see, looks like the supported Formats isn't initialized yet...?
![image](https://user-images.githubusercontent.com/10576957/83963302-52b10c80-a87b-11ea-9b25-0eed48324314.png)

By the way, I already called the `FreeMount.Init();`
What I did wrong?

**Comment by UlyssesWu** [comment]
Have you put `FreeMote.Plugins.dll` alongside the `FreeMote.Psb.dll` or in the `<exe path>\Plugins`?

**Comment by marcussacana** [comment]
It's all dll's in the root directory.

**Comment by marcussacana** [comment]
that said the dlls aren't in the root directory of the main program... maybe is that?

**Comment by UlyssesWu** [comment]
Maybe. Try put all dlls in the root directory of the main program, or in `<exe path>\Plugins`, or use the same `app.config` as FreeMote tools and then put all dlls in `<exe path>\lib`.

**Comment by marcussacana** [comment]
No lucky changing the diretory, let me try add as reference.

**Comment by UlyssesWu** [comment]
There seems to be a bug if you are using `Release` mode. I'm fixing it.

**Comment by marcussacana** [comment]
Can you add optional path paramter to the static `FreeMount.Init` method?
Currently he only allways set null to the path paramter.

**Comment by UlyssesWu** [comment]
> Can you add optional path parameter to the static FreeMount.Init method?

OK, I will add that.

```
var Resource = new ImageMetadata
{
     Compress = PsbCompressType.Tlg,
     Name = $"{ID}.tlg"
};
Resource.SetData(Texture);
```
Did you set `Resource.Resource = new PsbResource()` ?

**Comment by marcussacana** [comment]
Nop, the code is exactly this one
![image](https://user-images.githubusercontent.com/10576957/83963887-6f4f4380-a87f-11ea-9b57-ef2b54432902.png)

**Comment by UlyssesWu** [comment]
Try the latest code and if that works, you will get an exception because `SetData` requires `ImageMetadata.Resource` to be set.

**Comment by marcussacana** [comment]
Yeah, after set the directory in the Init method, the file formarts are initialized.
And as you said I get a exception because of the Resource;
Thanks.

Also, i'm creating a small plugin to the Paint.Net to Read/Write simple .pimg files..
Are you interested in a PR for this?

I am uncertain because I am making the code very simple, I think can have problems in games with a more complex pimg...? I only have few samples with me....

Then, not sure if you will want a 'incomplete' tool, after all i'm writing for my own usage.
![image](https://user-images.githubusercontent.com/10576957/83964152-26988a00-a881-11ea-98ad-5c7bcf738146.png)

**Comment by UlyssesWu** [comment]
I don't have much pimg samples either. If you are open-source it, I'll try it with my samples.

In fact I have just found a FreeMote bug in pimg processing code. Fixing.

**Comment by marcussacana** [comment]
Nahh, I'm doing very manually the thing...
I don't researched much about how your library API.
Then probabbly I'm doing in the hard way?
Well, I will send you a link when it's ready then.

**Comment by marcussacana** [comment]
Here, I did my shit :)
https://github.com/marcussacana/FreeMote/tree/master/FreeMote.PaintDN
With help of this I managed to edit a game interface even adding new buttons;

But have some problems that need to keep atention:
- Some layers in the .pimg can be empty, when exporting the current version of the plugin can fuck the  'z-index' of the empty layer.  
- The Paint.net don't support layer groups, as a workaround I created a simple 'directory' system in the layer names, the current algorithm is very simple and can cause problems if the .pimg have a group parent of another group. 

 To the first I suppose the way is to create a 'detectable' empty image (for example, draw a dot in all layer corners)
To the second... well, the way is forget it... Maybe write a PSD importer to the .PIMG will be better, looks like you already did a exporter after all...

I don't will do a PR because I don't know how you feel about include such uncertain code in your repo, but if you want it just say.

You can get the binary here as well: https://github.com/marcussacana/FreeMote/releases/tag/2.5.1

**Comment by UlyssesWu** [comment]
I've tested it with my very a few pimg samples and it works well so far.
In fact I haven't used paint.net before so I don't quite understand about the first "z-index" problem...

I probably won't merge your code, as a paint.net plugin, it should just be a standalone repo. However, if you or me decide to make a converter between pimg & psd (that is to extend the FreeMote.Psd plugin to support pimg), I would merge that. It's possible to load or create psd like I already did in that FreeMote plugin, but that is mainly for PhotoShop, since it uses layer groups. If you're not interested in that. I will put it in my "nice-to-have" list.

**Comment by marcussacana** [comment]
Sad, the creator did a amazing job after all, I saw that plugin before, Initially I planned to write a PSD importer, but after the lack of a ready-to-use and free libraries I forgot that idea and just wrote the plugin to the paint.net.

**Comment by imKota** [comment]
@UlyssesWu any news about export pimg to psd and import psd to pimg?

**Comment by UlyssesWu** [comment]
> @UlyssesWu any news about export pimg to psd and import psd to pimg?

@imKota Don't have time to implement this at the moment. You can try marcussacana's paint.net plugin.

**Comment by imKota** [comment]
> > @UlyssesWu any news about export pimg to psd and import psd to pimg?
> 
> @imKota Don't have time to implement this at the moment. You can try marcussacana's paint.net plugin.

@UlyssesWu marcussacana's paint.net plugin don't work :((

**Comment by imKota** [comment]
> > @UlyssesWu any news about export pimg to psd and import psd to pimg?
> 
> @imKota Don't have time to implement this at the moment. You can try marcussacana's paint.net plugin.

@UlyssesWu Do you plan to make these features (pimg->psd and psd->pimg)?
It would make it very easy to work.

**Comment by imKota** [comment]
@UlyssesWu
> Don't have time to implement this at the moment.

I'll be waiting

> You can try marcussacana's paint.net plugin.

It doesn't work correctly (psd->pimg saving doesn't work, groups don't work).
I usually use photoshop. So I tried exporting pimg to psd, editing it. 
Then I opened the modified psd file and tried saving it with pimg , but got an error.
