### ISSUE TITLE
Recent update broken the CLI command --extract

### ISSUE THREAD

**Issue by jszhtian** [UlyssesWu/FreeMote#45]
For Version 2.3 and Version 2.5 FreeMote PsbDecompile
PsbDecompile will ignore extract command and directly output tlg file, like original C++ version PsbDecompile.
But it works fine on version 2.0.
------------
问题描述: 2.5和2.3版本PsbDecompile的extract参数无效。
程序行为和原始C++版本一致，直接输出tlg文件。
游戏类型:M2_KrkrZ
Test Game:
CafeStella (Yuzu Soft)
![image](https://user-images.githubusercontent.com/23244094/91981002-74aa1600-ed28-11ea-8073-d18567fbfbb2.png)
![image](https://user-images.githubusercontent.com/23244094/91981447-28aba100-ed29-11ea-87d6-64b0a01d80c3.png)

**Comment by UlyssesWu** [comment]
Fixed by remove `--extract` argument. ✌
Try the latest v2.6.0 release.

BTW, there is no "original C++ version" for PsbDecompile.
