### ISSUE TITLE
Error unpacking previously repacked .psb files

### ISSUE THREAD

**Issue by imKota** [UlyssesWu/FreeMote#48]
Hello, @UlyssesWu 

Tested on versions:
```
PsbDecompile - 2.5.0.0, 2.6.0.0, 2.7.0.0
PsBuild - 2.5.0.0, 2.6.0.0, 2.7.0.0
```

Unpack **config_message_en.pimg**:
```
./PsbDecompile.exe config_message_en.pimg
FreeMote PSB Decompiler
by Ulysses, wdwxy12345@gmail.com
9 Plugins Loaded.

Decompiling: config_message_en
Done.
```

Repacking modified files in **config_message_en.pure.pimg**:
```
 ./PsBuild.exe config_message_en.json
FreeMote PSB Compiler
by Ulysses, wdwxy12345@gmail.com
9 Plugins Loaded.

Compiling config_message_en ...
Compile config_message_en done.
Done.
```

I try to unpack the created **config_message_en.pure.pimg** and get an error:
```
# ./PsbDecompile.exe config_message_en.pure.pimg
FreeMote PSB Decompiler
by Ulysses, wdwxy12345@gmail.com
9 Plugins Loaded.

Decompiling: config_message_en.pure
System.NullReferenceException: Object reference does not point to an instance of an object.
   в FreeMote.TlgImageConverter.ReadTlg(BinaryReader src, TlgMetaData info)
   в FreeMote.TlgImageConverter.ReadAndGetMetaData(BinaryReader file, TlgMetaData& md)
   в FreeMote.Psb.PsbResHelper.OutputImageResources(PSB psb, FreeMountContext context, String name, String dirPath, PsbExtractOption extractOption, PsbImageFormat extractFormat)
   в FreeMote.PsBuild.PsbDecompiler.OutputResources(PSB psb, FreeMountContext context, String filePath, PsbExtractOption extractOption, PsbImageFormat extractFormat, Boolean useResx)
   в FreeMote.PsBuild.PsbDecompiler.DecompileToFile(String inputPath, PsbExtractOption extractOption, PsbImageFormat extractFormat, Boolean useResx, Nullable`1 key)
   в FreeMote.Tools.PsbDecompile.Program.Decompile(String path, Boolean keepRaw, PsbImageFormat format, Nullable`1 key)
Done.

```
After repacking the changed files, in the .psb archive one file is broken `0 bites`

![image](https://user-images.githubusercontent.com/24241471/100805803-64e1c100-3440-11eb-8e9d-54b6beb76e6c.png)

But in the original archive it is working `1305 bites`

![image](https://user-images.githubusercontent.com/24241471/100805845-72974680-3440-11eb-9d42-2c8b8c8adb79.png)

Could you please fix this?

[config_message_en.zip](https://github.com/UlyssesWu/FreeMote/files/5625903/config_message_en.zip)

**Comment by UlyssesWu** [comment]
The most recent FreeMote builds (with 2.7.0.0 version number) are unstable (you can see there is "[WIP]" on commit comment).
If you switch back to https://github.com/UlyssesWu/FreeMote/releases/tag/v2.6.0 everything should just be fine. 

FreeMote v2.7 is a breaking-change version to introduce full support for PSBv4 (usually for EMT PSB in recent games). It's still WIP now, do not expect it working. But this issue could be a potential bug, I'll fix that in later commits. Thanks!

**Comment by imKota** [comment]
@UlyssesWu 
> If you switch back to https://github.com/UlyssesWu/FreeMote/releases/tag/v2.6.0 everything should just be fine.

if you read the very beginning, you can see what I tested starting from version 2.5.0, then on version 2.6.0 and ended up checking on 2.7.0. 

You can check on the file that I attached to the post. I think this is a bug)

Thanks for your work))

**Comment by UlyssesWu** [comment]
I tried the 3 steps (decompile - build - decompile) with fresh FreeMote v2.6, no error occurs. If I use the latest 2.7 build, I get the same error.

**Comment by imKota** [comment]
@UlyssesWu This is strange...
> I tried the 3 steps (decompile - build - decompile) with fresh FreeMote v2.6, no error occurs. If I use the latest 2.7 build, I get the same error.

The problem arises after modifying files in Photoshop. The file names are identical, the sizes are slightly changed. But, in theory, this should not influence the same?

Try editing files, repacking and unpacking

[video](https://drive.google.com/file/d/1-ph1MFzq1xjgbfNR6aDgNqSa9zdZbvYI/view?usp=sharing)

**Comment by imKota** [comment]
@UlyssesWu or just try repack my files `284.png, 285.png, 286.png, 287.png, 288.png, 289.png` 
from **edited/config_message_en** and get the same error:D

**Comment by UlyssesWu** [comment]
Got an error, but not the message you attached (that's for the v2.7 case).

In v2.6 it's `System.ArgumentOutOfRangeException`. I will have a look at it later.

**Comment by imKota** [comment]
> В v2.6 это `System.ArgumentOutOfRangeException`. Я посмотрю на это позже.

Yes, this is it. 
Thank you, I'll wait for the news!

**Comment by UlyssesWu** [comment]
The latest CI build has this issue fixed, please have a try. 
This is a bug only happens on pimg type PSB with some exactly same images (e.g. `284.tlg` & `286.tlg` in your PSB).

Although the 2.7 CI build works for your pimg PSBs, it's still not safe to use a WIP version. In particular, the current build will fail when building EMT (motion type) PSBs. It's recommend to upgrade to the v2.7 stable release once it's released.

**Comment by imKota** [comment]
@UlyssesWu thanks!
