### ISSUE TITLE
[RGBA4444_SW][RGBA5650_SW] 提取图像花屏

### ISSUE THREAD

**Issue by skilittle** [UlyssesWu/FreeMote#49]
提取motion时出现了大量的花屏图像
![tex-texture](https://user-images.githubusercontent.com/53262738/103021611-660c9680-4585-11eb-8b31-a19029de0345.png)

[game_char02.zip](https://github.com/UlyssesWu/FreeMote/files/5736343/game_char02.zip)

**Comment by UlyssesWu** [comment]
尝试CI版本：https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts
2.7版本仍在开发中，对于motion PSBv4是不稳定的。但你的样本是motion PSBv3，还可以使用。
当FreeMote v2.7正式版本发布时，请尽快换用正式版本。

**Comment by skilittle** [comment]
> 尝试CI版本：[https](https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts) :
> //ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts 2.7版本仍在开发中，对于Motion PSBv4是正确的。但你的样本是motion PSBv3，还可以使用。
> 当FreeMote v2.7正式版本发布时，请尽快换用正式版本。

我已经尝试使用大佬所提供的版本，大部分文件都成功解出了，但是还是有个别文件花屏了，有待正式版能够修复
![image](https://user-images.githubusercontent.com/53262738/103102911-58c0dc00-4659-11eb-9b9b-331318250e9a.png)
[Uploading cgmode.psb.zip…]()

**Comment by UlyssesWu** [comment]
> Uploading cgmode.psb.zip…

样本没传成功，再传一次。

**Comment by skilittle** [comment]
> > Uploading cgmode.psb.zip…
> 
> 样本没传成功，再传一次。

[cgmode.psb.zip](https://github.com/UlyssesWu/FreeMote/files/5742128/cgmode.psb.zip)

**Comment by UlyssesWu** [comment]
还是从老地方下载CI版本测试。
如果还有别的样本有问题，继续传上来看看，这次记得检查是否上传成功。

**Comment by skilittle** [comment]
新发现一个不明的图像，它可能来自程序错误，测试版本v2.7.2
![image](https://user-images.githubusercontent.com/53262738/103809720-e4dcf580-5094-11eb-9049-a513e19e3858.png)

样本文件:
[radialline.psb.zip](https://github.com/UlyssesWu/FreeMote/files/5777671/radialline.psb.zip)
