### ISSUE TITLE
[VAG] Error occurs while extracting `sound.psb`  (提取sound.psb中的部分文件时出现错误)

### ISSUE THREAD

**Issue by skilittle** [UlyssesWu/FreeMote#50]
We're currently working on extracting a PSV game _Is the Order a Rabbit?? Wonderful Party!_. The file `sound.psb` within the game files was unpacked successfully, and from which we got a lot of PSB files. Somehow, a part of files of those PSB files can't be further unpacked.
![image](https://user-images.githubusercontent.com/53262738/103671630-20ed5900-4fb6-11eb-84f4-aa78e14f77ae.png)

Here is the sample:
[err.zip](https://github.com/UlyssesWu/FreeMote/files/5771360/err.zip)

**Comment by UlyssesWu** [comment]
Planned in v2.8.
References:
https://www.psdevwiki.com/ps3/Multimedia_Formats_and_Tools#VAG
https://forum.devchroma.nl/index.php?topic=9.0
https://bitbucket.org/SilicaAndPina/cxml-decompiler/src/master/AppInfoCli/VAG.cs
https://github.com/vgmstream/vgmstream/blob/9e971af29239e79c387ea709ccebd9d72bb12ce9/src/meta/vag.c
To encode, we may have to try vagconv(2).

**Comment by skilittle** [comment]
> Planned in v2.8.
> References:
> https://www.psdevwiki.com/ps3/Multimedia_Formats_and_Tools#VAG
> https://forum.devchroma.nl/index.php?topic=9.0
> https://bitbucket.org/SilicaAndPina/cxml-decompiler/src/master/AppInfoCli/VAG.cs
> https://github.com/vgmstream/vgmstream/blob/9e971af29239e79c387ea709ccebd9d72bb12ce9/src/meta/vag.c
> To encode, we may have to try vagconv(2).

Sorry, I don't know about PSB file structure

**Comment by UlyssesWu** [comment]
> > Planned in v2.8.
> 
> Sorry, I don't know about PSB file structure

Yeah, I'm sorry about that. You may want to impove your English reading comprehension skill first.
好好学英语，更重要的是要理解英语的表达方式，读一段话要和English speaker一样思考，而不是说看到“we”就翻译成“我们”，就理解成是要你来做这个。

**Comment by skilittle** [comment]
> > > Planned in v2.8.
> > 
> > 
> > Sorry, I don't know about PSB file structure
> 
> Yeah, I'm sorry about that. You may want to impove your English reading comprehension skill first.
> 好好学英语，更重要的是要理解英语的表达方式，读一段话要和English native speaker一样思考，而不是说看到“we”就翻译成“我们”，就理解成是要你来做这个。

我知道你的意思，但是我看到你给我的参考资料以为你需要让我去研究才做此回复

**Comment by UlyssesWu** [comment]
@skilittle 这次你提的两个issue都结了（另一个是 #51 ）。
如果有重打包的需要，需要参照[wiki](https://github.com/UlyssesWu/FreeMote/wiki/Audio#hevag)说明找到对应的编码（Encode）用工具。

**Comment by skilittle** [comment]
> @skilittle这个你提的两个组织都结了（另一个是[＃51](https://github.com/UlyssesWu/FreeMote/issues/51)）。
> 如果有重打包的需要，需要参照[wiki](https://github.com/UlyssesWu/FreeMote/wiki/Audio#hevag)说明找到对应的编码（Encode）用工具。

非常感谢大佬！
