### ISSUE TITLE
[CI4_SW][Fonts]字体提取后出现花屏现象

### ISSUE THREAD

**Issue by cdwcgt** [UlyssesWu/FreeMote#52]
Build version: 2.7.2
[Sample file](https://cdwcgt-my.sharepoint.com/:u:/g/personal/cdwcgt_cdwcgt_top1/EYLTXka1Y0xIoGE3HmGuH6kBj-DSF4U3noEOtzUdNn3cUA?e=caKlRR)(因为github传不上就扔到OD了)
![image](https://user-images.githubusercontent.com/34775378/104831718-c796fb00-58ce-11eb-95e7-9096215d9825.png)

**Comment by UlyssesWu** [comment]
尝试最新的CI版本：https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts
CI版本仍然是不稳定的，另一个功能还在开发中。当2.8正式版本发布时，请换用正式版本。

**Comment by cdwcgt** [comment]
> 尝试最新的CI版本：https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts
> CI版本仍然是不稳定的，另一个功能还在开发中。当2.8正式版本发布时，请换用正式版本。

好的（速度好快
