### ISSUE TITLE
[Wiki] Add some information about unknown params

### ISSUE THREAD

**Issue by TheEZIC** [UlyssesWu/FreeMote#57]
I saw -l and -a (helped me with image extraction) params in #40 . What they do? Please document them.

**Comment by UlyssesWu** [comment]
https://github.com/UlyssesWu/FreeMote/wiki

> Type -h command for tools' instructions. For example, if you don't know how to use PsBuild, just type PsBuild -h; If you don't understand PsBuild "info-psb" command (what's that or how to use that), type PsBuild info-psb -h.

`PsBuild info-psb -h`

```
Options:
  -?|-h|--help           Show help information
  -i|--intersect         Only pack files which existed in info.psb.m
  -p|--packed            Prefer using PSB files rather than json files in source folder
  -k|--key <KEY>         Set key (get file name from input path)
  -l|--length <LEN>      Set key length. Default=131
  -1by1|--enumerate      Disable parallel processing (can be slow but save a lot memory)
  -double|--json-double  (Json) Use double numbers only (no float)
```
