### ISSUE TITLE
[PsBuild] PSB -> PSD conversion

### ISSUE THREAD

**Issue by UlyssesWu** [UlyssesWu/FreeMote#6]
It may be implemented in spring 2019 if I'm still alive at that time.

**Comment by imKota** [comment]
Hey, @UlyssesWu How to use this?

**Comment by UlyssesWu** [comment]
> Hey, @UlyssesWu How to use this?

@imKota Sorry, this only works for motion PSB (EMT etc.). `EmtConvert pack -s PSD xxx.psb`
