### ISSUE TITLE
[PsbDecompile] file names in info-psb may contain path

### ISSUE THREAD

**Issue by TheEZIC** [UlyssesWu/FreeMote#60]
I got exceptions when decompile this files:
https://mega.nz/file/dSp0Wapa#48Xpqsvm2FdAbZI7PTb75X6md1XWwkie-pUMOncjquk
I Try to use psb-info and image. Not one of them worked. (key is 523aad2de7132)

**Comment by UlyssesWu** [comment]
This sample has been submitted by someone else before and I'm aware of this. Will get it supported later.

**Comment by TheEZIC** [comment]
What a problem causes this exception?

**Comment by UlyssesWu** [comment]
Oops, there is still something wrong about `sound.psb` thanks to the _amazing_ M2
