### ISSUE TITLE
[ASTC_8BPP] Legend of Mana Remake Psb.m texture file issue

### ISSUE THREAD

**Issue by MrVtR** [UlyssesWu/FreeMote#63]
Hello, I'm trying to extract some textures from Legend of Mana Remake, the files are in psb.m extension. I was able to extract the tetxures with FreeMote PsbDecompile, but the result is kinda glitchy, is there an way to fix the image or extract normally?

In the attachment I'm uploading one sample file and the image result that I obtained if it helps to study the sample
[Legend_of_Mana_Sample.zip](https://github.com/UlyssesWu/FreeMote/files/6791994/Legend_of_Mana_Sample.zip)

**Comment by UlyssesWu** [comment]
Currently unsupported texture format - `ASTC_8BPP`. Couldn't find a handy decoder/encoder. Will try to get it supported.

**Comment by MrVtR** [comment]
> Currently unsupported texture format - `ASTC_8BPP`. Couldn't find a handy decoder/encoder. Will try to get it supported.

Thanks a lot, doing some extraction, I found on the .json of psbDecompile the same texture format now here, I'm trying to search for a ASTC_8PP decompresser, but no clue where to find(I only found an Compresser to ASTC_8PP)
And Crystal Tile tool doesn't support it too(I used to use it with NDS Tiled textures normally)
Thank you very much if you can take a look on it!

**Comment by UlyssesWu** [comment]
With the latest commit it's possible to decode ASTC_8PP images. 
Encoding is not working for now and might be implemented later.

You can try the CI build:
https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts

**Comment by MrVtR** [comment]
> With the latest commit it's possible to decode ASTC_8PP images.
> Encoding is not working for now and might be implemented later.
> 
> You can try the CI build:
> https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts

Thanks, the Decompile function worked without any issues!

**Comment by UlyssesWu** [comment]
With an external encoder it's now possible to encode ASTC, too. [wiki](https://github.com/UlyssesWu/FreeMote/wiki/Plugins-&-External-Tools#freemoteastc)

Try CI build: https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts

To encode ASTC, you must download [astcenc](https://github.com/ARM-software/astc-encoder/releases) and put the `.exe` files into `FreeMoteToolkit\Tools` folder first.
