### ISSUE TITLE
[Question] Psbuild with multiple image files(or compiling non image attached json)

### ISSUE THREAD

**Issue by lsg97** [UlyssesWu/FreeMote#65]
Hi, I've been trying to use FreeMote to convert pure psb with my json files but It doesn't work right.
I think it is because of multiple image files that I have, doesn't work with your FreeMote.
But your Psbdecompile which I made json files seems work right.
Could you examine my json file that I could convert it to pure psb using Psbcompile.cs.
I think it is because my json file isn't combined with 2 image files.

ps. I've tried modding resx.json file to direct image files adding scripts like "Resources": {0}, "tex#000.png";
and renaming image files but Psbbuild.exe keeps saying "[warn] [0] is not used"

[c00570.zip](https://github.com/UlyssesWu/FreeMote/files/6950082/c00570.zip)

**Comment by UlyssesWu** [comment]
Your json didn't specify the resources correctly. I have no idea what you modified, you should have provided the original PSB, so that I can confirm whether it's a bug of FreeMote, or it's just your bad manual modification.

**Comment by UlyssesWu** [comment]
![image](https://user-images.githubusercontent.com/4312781/128621057-b9bc7870-d230-44b8-a377-0d6c54f3c380.png)

1. `PsBuild.exe c00570.json` Get a PSB without textures.
2. `PsBuild.exe link c00570.puse.psb tex#001.png tex#002.png` Get PSB with textures using link feature.

This is an **external texture PSB** (textures not in PSB), if you want to view it in FreeMoteViewer, you must link it. This is already noted in wiki. I guess you didn't read that.

**Comment by lsg97** [comment]
Geez, thanks.
I've read wiki but I've been linking sources psb to image and it keeps saying System.NullReferenceException error.
Now that I've tried after converting json to pure.psb and linking it to image it works!
You saved my day. What a great program!
Thanks again.

**Comment by UlyssesWu** [comment]
> I've read wiki but I've been linking sources psb to image and it keeps saying System.NullReferenceException error.

I have no idea about that error but if your source PSB is encrypted (not pure) it could happens. Anyway I can only confirm with complete error message.

**Comment by lsg97** [comment]
Uh-oh, if I click motion buttons FreeMoteViewer crashes.
I guess there's something wrong with my source files like you've said.
I hope this error does some help to FreeMote(sending you the source files).
Thanks.
[c00570.zip](https://github.com/UlyssesWu/FreeMote/files/6950268/c00570.zip)

**Comment by lsg97** [comment]
And this is what I get when I link directly with source psb.

E:\FreeMote>psbuild link c00570.psb c00570_tex000.png c00570_tex001.png
FreeMote PSB Compiler
by Ulysses, wdwxy12345@gmail.com
12 Plugins Loaded.

System.NullReferenceException: Object reference not set to an instance of an object.
   at FreeMote.Psb.PSB.LoadFromDullahan(Stream stream, Int32 detectSize, Nullable`1 namePosition)
   at FreeMote.Psb.PSB..ctor(String path)
   at FreeMote.Tools.PsBuild.Program.Link(String psbPath, List`1 texPaths, PsbLinkOrderBy order)
Link c00570 done.
Done.

**Comment by UlyssesWu** [comment]
The only crash I met so far, is clicking a specific motion's button for many times. If you just click once (waiting for it to play), it should be OK?

> And this is what I get when I link directly with source psb.

Just checked your PSB. Your "PSB" is not started with "PSB\0" file signature (not actually a PSB file), that caused this problem. It seems that the game prepended some file name info into that file, or it's your extraction tool's issue.

**Comment by lsg97** [comment]
My bad, my bad... haha.
Powerful tool you've made.
Thanks.

**Comment by UlyssesWu** [comment]
> The only crash I met so far, is clicking a specific motion's button for many times. 

It's still a thing, just got it fixed. Thanks.
