### ISSUE TITLE
[Question] PS4 PSB.M Font File PsbDecompile chunk images

### ISSUE THREAD

**Issue by l0ve2s** [UlyssesWu/FreeMote#67]
**please confirm**
Thank you.
[textfont60.psb.decompressed.zip](https://github.com/UlyssesWu/FreeMote/files/6986690/textfont60.psb.decompressed.zip)
PS4 PSB 
![0 - 0](https://user-images.githubusercontent.com/88938174/129450792-4a0b4e98-0270-4bb3-a1f3-425a85db7c68.png)

**Comment by l0ve2s** [comment]
Thank you.

**Comment by UlyssesWu** [comment]
Should be fixed. Try the [latest CI build](https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts).
