### ISSUE TITLE
InvalidDataException when unpack archive PSB due to irregular .m name

### ISSUE THREAD

**Issue by skilittle** [UlyssesWu/FreeMote#68]
旧版
![image](https://user-images.githubusercontent.com/53262738/137317610-a0146478-a530-4d0a-82d1-8c48bf513267.png)
新版
![image](https://user-images.githubusercontent.com/53262738/137317657-fc3f6e97-2704-4346-a2f7-d250787866e6.png)
样本文件较大,我把它放在了我的磁盘里（它会在48小时后失效，请尽快获取）
http://data.ancgk.cn:8000/ps/

**Comment by skilittle** [comment]
> 感谢，已复现问题。目测主要是因为info psb中的文件是否有压缩是无规律的，或者有内在规律但是还没摸索清楚。前几个版本在其他psb.m上出现问题所以调整了下策略。

除此之外，在新版本中大量音频文件的格式变为了xwma
![image](https://user-images.githubusercontent.com/53262738/137332403-bbd8465f-0122-4c88-93a0-4adecbcf10fe.png)

**Comment by UlyssesWu** [comment]
xwma样本何在

**Comment by skilittle** [comment]
> xwma样本何在

我检查了一下，是我提取的psb文件被二次封装过了
