### ISSUE TITLE
PSP .bin & .psb.m (Akatsuki no Goei Trinity)

### ISSUE THREAD

**Issue by MishaIac** [UlyssesWu/FreeMote#70]
Hi. I'm having problem with unpacking files from the PSP version of Akatsuki no Goei Trinity.
I have two files: fileinfo.psb.m and filebody.bin.
I tried to unpack fileinfo.psb.m and it worked. A .json file came up with all the file names of all the files in filebody.bin. However, no matter how hard I tried, I could not unpack filebody.bin. Through EmtConvert also does not work. Although, the key and length are correct, because with it I was able to unpack fileinfo.psb.m.
Key: ae3bb93923bf8
Key length: 0x83 (131)
![image](https://user-images.githubusercontent.com/47920105/146596927-0bf4273c-d5f9-4409-82f5-d53cd5478670.png)
Here is a sample (unfortunately, the file has 277 mb, so I had to upload to google drive): https://drive.google.com/file/d/1dE6sL7aiPsZPflnKiconQtIDID6Vvx1x/view?usp=sharing
Only fileinfo.psb.m: [akatsuki trinity fileinfo.psb.m.zip](https://github.com/UlyssesWu/FreeMote/files/7737410/akatsuki.trinity.fileinfo.psb.m.zip)

**Comment by UlyssesWu** [comment]
Thanks for providing the sample. This is kind of different with other psb.m files I met before. Will try to support it later.

**Comment by MishaIac** [comment]
By the way, I have another .bin file, but from another PSP game on the M2 engine. The header says "PSB" not "mdf", so it shouldn't be encrypted with a key. However, Freemote cannot unpack the archive. Only a .json file appears that says it's Sound Archive, and the folder where the unpacked files should be is empty.
Maybe this file is the same type as the file from Akatsuki no Goei Trinity, but without the encryption? I can send you a sample if you need it, but it's 700 mb.
Json file from this filebody.bin: 
![image](https://user-images.githubusercontent.com/47920105/146640053-4f9002a9-4af9-4f3d-b188-640a6d245c62.png)

**Comment by UlyssesWu** [comment]
Sound Archive is a known type of PSB, not related with Archive (info.psb.m). 
For known Sound Archive, FreeMote converts the audio resources in it to WAV and save to the folder, but apparently this PSB's resource is not convertable for current FreeMote builds. 
If you'd like to share the file I may have a look. But since the Audio support in FreeMote is quite experimental, do not expect it can be supported soon. You can also use `PsbDecompile -raw` to get the raw resources in it and convert it by yourself.
Or, our friend [vgmstream](https://github.com/vgmstream/vgmstream) has better support for game audio. Maybe it will be able to load PSB and play the audio which FreeMote can not convert.

**Comment by MishaIac** [comment]
But it's not a sound archive. This archive contains scenario_body.bin, scenario_info.psb.m, etc.

**Comment by MishaIac** [comment]
So it is strange that it is labeled as a sound archive. If you use `-raw`, the output will be one file of 3 kb, although the archive itself has 700 mb.

**Comment by UlyssesWu** [comment]
Oh, ok. I think you drag & drop the .bin file to PsbDecompile, but it's not a correct behaviour.
The wiki has told you, .bin file is not handled by FreeMote. Instead, it's unpacked when you process info.psb.m.

However, since the info.psb.m is a new type, the .bin file is not handled either.

**Comment by MishaIac** [comment]
I tried to unpack the file with `info-psb`, and this error appeared. By the way, the same error when I tried to unpack the archive from Akatsuki no Goei Trinity. Maybe they really have the same type.
![image](https://user-images.githubusercontent.com/47920105/146641698-f358a3b9-83e8-498e-baa9-143537c9de09.png)

**Comment by MishaIac** [comment]
Oh, I understand that this is a new type. I will wait for the support of this type. Thank you and good luck.

**Comment by UlyssesWu** [comment]
Do you ever change their file names? Keep in mind that archive files' names should not be changed.
Most archive files are "file_info.psb.m" + "file_body.bin" pattern. But now I see your samples with "namebody.bin" and "nameinfo_body.bin". Have you changed their names from "name_body.bin"?

**Comment by MishaIac** [comment]
Yes, I changed the file name. But from the beginning, it had the name `INSTALL.BIN`, and was something like the installation file for the PSP, and had a `PGD` in header. From it, I unpacked the file with the `mdf` header. It turns out that the name of the file is not known. Or should it be `INSTALL.BIN`?

**Comment by MishaIac** [comment]
Here's what's in EBOOT.BIN
![image](https://user-images.githubusercontent.com/47920105/146671983-da977fd6-b8de-47c4-aa0e-f3925110368c.png)

**Comment by UlyssesWu** [comment]
For now FreeMote only try to find "file**_body.bin**". (No need to try this name, it still fails because of new info.psb.m type)
I will add a commandline option `-b`  in next version, to allow setting `body.bin` path.

**Comment by MishaIac** [comment]
So the correct name for the archive should be `INSTALL.BIN`, that it can be unpacked when there is support for this type?

**Comment by UlyssesWu** [comment]
The [latest CI build](https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts) should be able to extract your files with command:
 `PsbDecompile info-psb "fileinfo.psb.m" -k ae3bb93923bf8 -l 131 -b "filebody.bin"` 
(use `-b` to set body.bin path, and don't use `-a` because PsbDecompile won't extract info-psb recursively).

**Comment by UlyssesWu** [comment]
One more thing, `"voice_body.bin": [55968,1684597248]` indicates that it's located at 1684597248 (1684MB) of filebody.bin, which is not correct. So it cannot be extracted.

**Comment by MishaIac** [comment]
> The [latest CI build](https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts) should be able to extract your files with command: `PsbDecompile info-psb "fileinfo.psb.m" -k ae3bb93923bf8 -l 131 -b "filebody.bin"` (use `-b` to set body.bin path, and don't use `-a` because PsbDecompile won't extract info-psb recursively).

Yes, everything unpacked, thank you very much. But now I have another problem. How do I unpack the archives from filebody.bin? I now want to unpack scenario_body.bin, but it does not work, an error appears both through PsbDecompile and through EmtConvert. The key is the same, right?

**Comment by MishaIac** [comment]
> One more thing, `"voice_body.bin": [55968,1684597248]` indicates that it's located at 1684597248 (1684MB) of filebody.bin, which is not correct. So it cannot be extracted.
> 
> And, since I have no knowledge about .pmf files, I cannot decode it to normal video files with tools I found. I have no idea whether it's encrypted.

voice_body.bin is located directly in the .iso folder of PSP_GAME\USRDIR, where fileinfo.psb.m
![image](https://user-images.githubusercontent.com/47920105/147417769-d10474bc-76e0-4e23-a798-2370c94ce933.png)

**Comment by MishaIac** [comment]
> Yes, everything unpacked, thank you very much. But now I have another problem. How do I unpack the archives from filebody.bin? I now want to unpack scenario_body.bin, but it does not work, an error appears both through PsbDecompile and through EmtConvert. The key is the same, right?

I solved the problem by first encrypting scenario_info.psb.m to mdf with EmtConvert and then unpacking it with PsbDecompile. (but is this how it should be?) Most likely I couldn't decompile because the .bin file is encrypted, but the psb.m is not.

p.s. I could not decrypt the .bin file with EmtConvert. EmtConvert just hangs, and doesn't even display any error.

**Comment by MishaIac** [comment]
There are also problems with fonts. Freemote unpacks the wrong textures.
![0 - 0](https://user-images.githubusercontent.com/47920105/147418344-c8f1e9c1-fba0-4490-acbb-317361169bc3.png)
[akatsuki no goei font samples.zip](https://github.com/UlyssesWu/FreeMote/files/7777479/akatsuki.no.goei.font.samples.zip)

**Comment by UlyssesWu** [comment]
OK, I will take a look of these problems later.

**Comment by UlyssesWu** [comment]
> I could not decrypt the .bin file with EmtConvert

I have explained this before:  **body.bin file is not handled by FreeMote**. Instead, it's unpacked when you process info.psb.m.

body.bin is a simple combination of many PSB files. Without info.psb.m, you can hardly (but still possible sometimes) divide body.bin into a sort of files. That's why **body.bin file is not handled by FreeMote**.

**Comment by UlyssesWu** [comment]
Both of your problems should be fixed now, try [latest CI build](https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts).

If there is still a problem, just reply here.

**Comment by MishaIac** [comment]
Yeah, it works perfectly. Thank you very much.
> I could not decrypt the .bin file with EmtConvert

And sorry for asking such stupid questions :)

**Comment by MishaIac** [comment]
Now there is a problem with unpacking motion files psb.m from the motion_body.bin archive.
Is it possible that it is an unsupported type? Or am I doing something wrong again?
[akatsuki no goei motion sample.zip](https://github.com/UlyssesWu/FreeMote/files/7781390/akatsuki.no.goei.motion.config.psb.m.zip)

**Comment by UlyssesWu** [comment]
Try latest build again.

**Comment by MishaIac** [comment]
Yes, the motion files are unpacked normally. Thank you.

But, now there's another problem. Haaah... This time the latest CI build Freemote gives an error when trying to unpack image files from image_body.bin, and again, if you use the old version of Freemote then the file will unpack, but the textures will be wrong.
[akatsuki no goei image samples.zip](https://github.com/UlyssesWu/FreeMote/files/7783441/akatsuki.no.goei.image.samples.zip)

_How many more unsupported psb formats will there be in PSP...?_

**Comment by UlyssesWu** [comment]
The latest build will extract images correctly. However, if you run `PsbDecompile xxx.psb.m`, both combined images and piece images will be generated, and sadly, **the pieces are actually used when repacking**. That's because the combined images are always normal 32bpp PNGs, while the pieces kept the original format - which are 8bpp indexed PNGs. For repack, we need to keep original format.

The common (easy) method to convert a 32bpp PNG to 8bpp indexed PNG causes serious color loss, so it's unable to use combined images for repack. As a result, if you want to modify the images for now, you should modify the pieces. 
I will continue to improve this when I have time (won't be quick).

If you just going to extract, not repack, you can use `PsbDecompile image xxx.psb.m`. This will generate combined images only.

**Comment by MishaIac** [comment]
Everything works. Thank you very much.

Right now I want to transfer the partial Russian translation of Akatsuki No Goei to the PSP version. I need to edit some small images from image_body.bin, so I think it shouldn't be a problem. However, when it's time to transfer the full translation (it should come out on PC first), then I'll have to edit the images with many pieces (like staffroll). I think by that time Freemote will be improved in this.

Again, thank you. I will definitely mention Freemote as the main tool with which I was able to make this patch, and also the author of the tool.
