### ISSUE TITLE
[Question] How do I get FreeMoteViewer.exe to launch?

### ISSUE THREAD

**Issue by HAHALOSAH** [UlyssesWu/FreeMote#71]
When I run FreeMoteViewer.exe and drag the psb file into the command prompt window and press enter, it just exits right away, what am I doing wrong?
![Screen Shot 2021-12-18 at 5 50 58 PM](https://user-images.githubusercontent.com/67280050/146660767-e734eddb-ae80-4786-86bf-9ac9d2c3941c.png)

**Comment by UlyssesWu** [comment]
Provide sample and do not hide things.

**Comment by HAHALOSAH** [comment]
[Here](https://drive.google.com/file/d/1f8S8JrPY8CDBroqAEYMOBftPlLirCDmD/view?usp=sharing) is the file I tried to view
https://drive.google.com/file/d/1f8S8JrPY8CDBroqAEYMOBftPlLirCDmD/view?usp=sharing

**Comment by UlyssesWu** [comment]
I can load this psb with FreeMoteViewer (FreeMote v3.1), without problem. Check your FreeMote files, or try on another computer.

**Comment by HAHALOSAH** [comment]
Can you link a download to a working FreeMoteViewer executable? I downloaded the FreeMote toolkit here https://github.com/UlyssesWu/FreeMote/releases

**Comment by UlyssesWu** [comment]
Your link is correct.
_Possible_ fail reasons:
1. You are not loading the file you sent to me.
2. Your system is lacking some VC++ Redistributable Packages or DirectX 9 updates.
3. Your anti-virus deleted or blocked some files in FreeMote. (maybe emotedriver.dll)
4. Your system blocked some files in FreeMote. (maybe Search keyword: "unblock file properties")

**Comment by HAHALOSAH** [comment]
I get the same result for running it with any real file, including text files, and it doesn’t seem to making a difference. DirectX and vc++ redistributable are both installed and my antivirus are off. Is there a list of system requirements?

**Comment by HAHALOSAH** [comment]
The mouse appears to load for a second before FreeMoteViewer exits

**Comment by HAHALOSAH** [comment]
I tried a different version of FreeMoteViewer, and now it closes the command prompt window when it runs

**Comment by UlyssesWu** [comment]
Try [latest build](https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts). If it cannot work either, I can only suggest you to try on another computer.

**Comment by HAHALOSAH** [comment]
The latest build is what causes the command prompt window to close, I've tried this on two computers, are there libraries I need to install?

**Comment by HAHALOSAH** [comment]
I just ran it in a different terminal app, this is what I get

```
FreeMote Viewer
by Ulysses, wdwxy12345@gmail.com

System.BadImageFormatException: Could not load file or assembly 'FreeMote.NET.dll' or one of its dependencies.  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)
File name: 'FreeMote.NET.dll'
   at FreeMote.Tools.Viewer.MainWindow..ctor()
   at FreeMote.Tools.Viewer.Program.<>c__DisplayClass0_0.<Main>b__0()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplicationExtensions.<>c__DisplayClass9_0.<OnExecute>b__0()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass144_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<ExecuteAsync>d__155.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at FreeMote.Tools.Viewer.Program.Main(String[] args)
```

**Comment by UlyssesWu** [comment]
> Your system blocked some files in FreeMote. (Search keyword: "unblock file properties")

1. Have you checked `FreeMote.NET.dll` and `emotedriver.dll` is not blocked?
2. What's you system's version (xp,win7,win10) and CPU architecture(x86,x64,arm) ?
3. Try install .NET Framework 4.8 if you haven't.

**Comment by HAHALOSAH** [comment]
Installing .NET and rebooting seems to of fixed it.
