### ISSUE TITLE
Hello Lady! Decrypt error

### ISSUE THREAD

**Issue by Jair4x1** [UlyssesWu/FreeMote#72]
Recently, the english patch for Hello Lady! has launched.
I extracted the .txt.scn and tried to decrypt the files with the latest version of the FreeMoteToolKit, but it shows this error:

![imagen](https://user-images.githubusercontent.com/94941399/151044139-334e03f1-fb82-47ee-bcea-25f69b675478.png)

It happens with every file and I can't decompile them.

Any help?

**Comment by UlyssesWu** [comment]
Where are samples?

**Comment by UlyssesWu** [comment]
Close due to no response.
