### ISSUE TITLE
[Question|info-psb] Can't extract "*_body.bin"

### ISSUE THREAD

**Issue by reinesarchisorte** [UlyssesWu/FreeMote#73]
Am i doing something wrong? I can't understand why it's trying to add _body.bin to existing file name. It may be that the key is wrong, but the error message should be different then. <a href="https://drive.google.com/file/d/19iSN3H_hgWtmSxeaX8faw1DHtotlUYp_/view?usp=sharing">File</a> if needed. Key should be "nx5ik27w2scm7".
<img width="1294" alt="Снимок экрана 2022-02-10 в 22 21 04" src="https://user-images.githubusercontent.com/30483762/153461758-1ca246d6-72b5-4813-bb69-df6e66eb8787.png">

**Comment by UlyssesWu** [comment]
https://github.com/UlyssesWu/FreeMote/wiki/PSB-Shells,-Types,-Platforms#name_bodybin

>  ({name}_body.bin) It's not directly handled by FreeMote tools (always use corresponding info.psb.m).

If you try the latest build (not latest release), it will show you a clear hint: 

https://github.com/UlyssesWu/FreeMote/commit/d56d9aa56e954732192115da50c904c39f50172e#diff-cf21cdb44ec6bac4a9f2912f2d25e8afadb8a4090d1fb04568c18d231e987916R422

**Comment by reinesarchisorte** [comment]
Thanks!
