### ISSUE TITLE
[EMT] Icon with resolution set in win format has been scaled and cannot be converted to krkr format

### ISSUE THREAD

**Issue by lightlesSo** [UlyssesWu/FreeMote#75]
The emote for krkr doesn't support resolution. But  the result of psbuild -p krkr has resolution property.
```
 "source": {
    "tex": {
      "icon": {
        "0000": {
          "attr": 1,
          "height": 91,
          "left": 3973,
          "metadata": {
            "zorder": 29
          `},`
          "originX": 40,
          "originY": 45,
        "resolution": 0.9,
          "top": 303,
          "width": 81
        },
        "0001": {`
```

If a psb file has resolution property .  There will be a wrong picture. 
I think it can be solved like this :
Enlarge the picture 1/resolution multiples. Set left=left/resolution top=top/resolution.
```
      "texture": {
        "ast": 0,
        "height": 4096,
        "pixel": "#resource#0",
        "type": "RGBA8",
        "width": 4096
      },
```
Set height=height/resolution ,width=width/resolution. 
Remove resolution property.

All resolutions need to be equal to others.

**Comment by UlyssesWu** [comment]
Thanks for the info, but where are samples?

**Comment by UlyssesWu** [comment]
> Enlarge the picture 1/resolution multiples
That's probably not a good idea because the scale-up will most likely ruin the image quality unless we use something like waifu-2x, but that will be unstable for some users without a good CPU/GPU. Maybe I will just remove "resolution" for krkr.

**Comment by UlyssesWu** [comment]
我使用EMT编辑器进行测试，对同一个设置了resolution的模型导出KRKR和WIN格式的PSB，结果证明KRKR模型支持resolution，你的说法似乎不成立，因此won't fix。

初步看来，resolution只是关系到该图片显示的清晰度，并不影响尺寸。
![image](https://user-images.githubusercontent.com/4312781/161413032-9d751975-2579-4bc1-8f2d-e50393457058.png)


WIN：
``` json
        "0197": {
          "attr": 0,
          "height": 126,
          "left": 2693,
          "metadata": null,
          "originX": 95,
          "originY": 63,
          "resolution": 0.25,
          "top": 722,
          "width": 191
        },
```

KRKR：
``` json
      "icon": {
        "ex_body_a": {
          "clip": {
            "bottom": 0.956521749,
            "left": 0.0430622026,
            "right": 0.9569378,
            "top": 0.04347826
          },
          "compress": "RL",
          "height": 126,
          "metadata": null,
          "originX": 95,
          "originY": 63,
          "pixel": "#resource#145",
          "resolution": 0.25,
          "width": 191
        }
      },
```

**Comment by UlyssesWu** [comment]
如果你有问题可以继续在此回复。

**Comment by UlyssesWu** [comment]
懂了，影响的是WIN格式texture中的尺寸。那么只能去掉resolution了

**Comment by lightlesSo** [comment]
抱歉 之前忙着做些事 忘了这里 现在还需要提供有错误的文件吗
win格式是否错误不知道,krkr和win格式在用FreeMoteViewer预览时都是正确的
assetbundle里的文件拆开是这样的图片
![2003031400_01_mid_tex000](https://user-images.githubusercontent.com/23395936/163802878-cca6124f-ea05-4a73-a1b9-4934f0c0152d.png)

按照krkr格式输出 其中的一部分是这样的


![tex-0051](https://user-images.githubusercontent.com/23395936/163802741-72edcc8c-0111-4091-a340-9fccfe507de9.png)

在krkr里会有这样的结果

![offset](https://user-images.githubusercontent.com/23395936/163802795-84628a71-9d7a-48ea-8c94-c12778ae9fba.PNG)

把图片放大后去掉resolution等价于把图片切成这样再放大 然后在krkr里才会正常显示

![tex-0052](https://user-images.githubusercontent.com/23395936/163802748-30c05898-abb8-4a39-a986-5d738e061502.png)






你现在用的是哪种方法呢
1.放大后再去掉resolution之后正常处理 这种情况需要所有的resolution相等

2先把icon的width和height乘resolution ,分割成小图后再对每个小图放大1/resolution的倍数  这时每个resolution可以不相等,不知道是否有这种情况

测试文件
https://mega.nz/file/tx0VwTha#XDFywuz-plOyl2dYYUb6-NhTMkTXXxr-2vViphqgjLs
