### ISSUE TITLE
爱上火车-Last Run!!     dx_真闇_私服a法被.psb      decompile     no work!

### ISSUE THREAD

**Issue by a1802lzw** [UlyssesWu/FreeMote#77]
FreeMote.PsbBadFormatException: Can not find Names segment, Dullahan load failed
   在 FreeMote.Psb.PSB.LoadFromDullahan(Stream stream, Int32 detectSize, Nullable`1 namePosition)
   在 FreeMote.Psb.PSB.DullahanLoad(Stream stream, Int32 detectSize)
   在 FreeMote.PsBuild.PsbDecompiler.Decompile(String path, PSB& psb, Dictionary`2 context, PsbType psbType)
   在 FreeMote.PsBuild.PsbDecompiler.DecompileToFile(String inputPath, PsbExtractOption extractOption, PsbImageFormat extractFormat, Boolean useResx, Nullable`1 key, PsbType type, Dictionary`2 contextDic)
   在 FreeMote.Tools.PsbDecompile.Program.Decompile(String path, Boolean keepRaw, PsbImageFormat format, Nullable`1 key, PsbType type, Dictionary`2 context)
Done.

**Comment by UlyssesWu** [comment]
必须提供样本，不然看不出问题

**Comment by UlyssesWu** [comment]
你这个PSB是加密的（PSBv2），必须手动指定key：
`.\PsbDecompile xxx.psb -k 3xxxxxxxx`

每个游戏的Key都可能不同，你要自己找，这里不提供。

**Comment by a1802lzw** [comment]
阙然就不报，辛勿过
此游戏解包其他psb文件几乎都可以解压，目前只发现这一个，也许不是加密问题？
样本如下:
[dx_真闇_私服a法被.zip](https://github.com/UlyssesWu/FreeMote/files/8510565/dx_._.a.zip)

**Comment by UlyssesWu** [comment]
> 阙然就不报，辛勿过
若无提前声明，7天无回复的单子一律关闭。

这的确是一个加密的PSB。

至于其他psb文件可解压，原因是这个游戏复用前作的PSB，里面的PSB版本v2、v3、v4都有。
其中v3及以上的PSB可以实现无key读取（此技术称为Dullahan Load，可用于解包和查看，但无法重打包成加密的PSB，也就是不可以修改后放回原游戏），但v2不可以，只能用key解。
想必你解不开的这一批PSB是这个游戏复用的最老的一批PSB。

**Comment by a1802lzw** [comment]
**_如果你真的想表达尊重，就请及时回复，或者等你有空及时回复了再提问，而非用古文道歉。_**
明白了，会注意的
