### ISSUE TITLE
krkr不支持resolution属性

### ISSUE THREAD

**Issue by lightlesSo** [UlyssesWu/FreeMote#78]
如果json部分中有resolution属性的话, psbuild使用-k krkr参数生成的psb在FreeMoteViewer中显示正常 但是实际在krkr中会有错位现象. 

文件中所有resolution相同的情况下 把图片放大1/resolution的倍数,之后删去json文件中的resolution可以得到外观一样的结果.
这种情况可以在krkr中会正常显示

测试文件
https://mega.nz/file/J11UjapR#Muyuqv-WgtOOhlonR2judMoEniofyusuZrThBE_nAJ0

**Comment by UlyssesWu** [comment]
？我不是让你尝试新的release了吗？
https://github.com/UlyssesWu/FreeMote/releases/tag/v3.2.0

**Comment by lightlesSo** [comment]
sorry 我把relesase看出issue了,昨天我还很奇怪为什么要新开一个issue
现在是正常的 
给你添这么多麻烦 我该怎么谢罪
