### ISSUE TITLE
Having problem with decompiling .psb file

### ISSUE THREAD

**Issue by ArtoriaPendragon0** [UlyssesWu/FreeMote#79]
**Notice**: If you met a problem when you process your files with FreeMote, firstly you should read all pages of [wiki](https://github.com/UlyssesWu/FreeMote/wiki). Then you should provide samples (files which might help me to locate the problem, usually psb/json files) and describe how to reproduce the issue you met.
I'm trying to decompile .psb files with Freemote but it's not working. When I try opening PsbDecompile it opens immediately then it crashes I don't know why. The only one that's opening is EmtConvert. It says that I should input code but no matter what I write it says that it's incorrect. I don't know if I'm doing something wrong but this is what I'm writing: PsbDecompile info-psb -k 523aad2de7132 script_info.psb.m. So I even have the game's code. Any help would be appreciated.
![2022-06-03](https://user-images.githubusercontent.com/106391503/172000377-26bde2bd-cfc0-451f-859a-adb80e802a70.png)
.
![2022-06-04 (1)](https://user-images.githubusercontent.com/106391503/172000379-7fbab756-a837-44e1-b1f5-b652fcc4c39f.png)

![2022-06-04 (2)](https://user-images.githubusercontent.com/106391503/172000372-49b998a1-d3ac-4452-bf92-763beb7d57fb.png)
.

**Comment by UlyssesWu** [comment]
Try drag & drop PSB files to PsbDecompile.exe, and if that won't work for you, google and learn how to enter commands on CMD or Windows Terminal, and continue to ask questions only after you can understand this (on the first page of wiki):

> Type -h command for tools' instructions. For example, if you don't know how to use PsBuild, just type PsBuild -h; If you don't understand PsBuild "info-psb" command (what's that or how to use that), type PsBuild info-psb -h.

**Comment by ArtoriaPendragon0** [comment]
> Try drag & drop PSB files to PsbDecompile.exe, and if that won't work for you, google and learn how to enter commands on CMD or Windows Terminal, and continue to ask questions only after you can understand this (on the first page of wiki):
> 
> > Type -h command for tools' instructions. For example, if you don't know how to use PsBuild, just type PsBuild -h; If you don't understand PsBuild "info-psb" command (what's that or how to use that), type Ps
![2022-05-27 (3)](https://user-images.githubusercontent.com/106391503/172004566-0b7946a5-fe13-4923-af89-25c1ab0694e1.png)
Build info-psb -h.

Sorry this is my first time here so I may have posted on the wrong place. The problem is that PsbDecompile is crashing immediately when I open it. Only EmtConvert works, when I drag the file in it, it just writes the destination of the file. I tried writing EmtConvert -h but it said that the input is incorrect. The image I uploaded is what the program shows me before it crashes immediately. Again, sorry for the inconvenience!

**Comment by UlyssesWu** [comment]
You don't even understand "drag & drop PSB files to PsbDecompile.exe". I didn't say "open PsbDecompile.exe and drag & drop PSB files into it".
Watch the opeation in this page:
https://vk.com/@epiceagleteam-kirikiriz-emote

**Comment by ArtoriaPendragon0** [comment]
> You don't even understand "drag & drop PSB files to PsbDecompile.exe". I didn't say "open PsbDecompile.exe and drag & drop PSB files into it". Watch the operation in this page: https://vk.com/@epiceagleteam-kirikiriz-emote

Sorry I didn't pay attention it's my fault. Thank you very much for helping me!

**Comment by UlyssesWu** [comment]
No matter you want to be a translator, a hacker or just a CG collector, you should start learning how to use CMD (or WT), since most tools in this area are commandline tools.
