### ISSUE TITLE
Could anyone help me with ripping the OST from Pac-Man Dash!? [MT19937 MDF]

### ISSUE THREAD

**Issue by N-Games** [UlyssesWu/FreeMote#80]
I've got all the files that I need to have by following the audio guide and I have the psb.m files of the game, but I have absolutely no idea what to do no. Could anyone help me please?
[sound.zip](https://github.com/UlyssesWu/FreeMote/files/8838443/sound.zip)

**Comment by UlyssesWu** [comment]
You have to find the MDF key (a.k.a. info-psb key) in order to extract from psb.m files. Usually it's a hex string with 13 characters, like `ae3bb93923bf8`. You may find it in some ROM files or dll/exe files - I have no idea.

Besides, these files look too small for OST I think? Maybe there is no audio files in them.

**Comment by N-Games** [comment]
Alright, I'll try to find the MDF key. Also it should be the OST, since these files are located in the folder called sound. There are no other references for anything other audio related in the files as far as I know

**Comment by UlyssesWu** [comment]
When you found the key, use the following command:

`EmtConvert mdf -k <your MDF key> -l 131 title.psb.m`

**Comment by UlyssesWu** [comment]
I can decode them with these steps. Please ensure you're using the latest 3.2 release.
Use these decrypted files if you still can't.
[menu1_snd2.zip](https://github.com/UlyssesWu/FreeMote/files/8857778/menu1_snd2.zip)

**Comment by N-Games** [comment]
I'm indeed using the latest release (3.2), but it's getting even weirder: I'm able to extract snd2.psb.decompressed.psb, but I can extract menu1.psb.decompressed.psb for some reason. I really can't thank you enough for helping me out tho

**Comment by UlyssesWu** [comment]
Show me the program output, and maybe attach the resx.json file.

**Comment by N-Games** [comment]
Here:
![afbeelding_2022-06-08_082842353](https://user-images.githubusercontent.com/58544833/172547118-a8ff7803-5a46-4a33-aa88-28f43637d5d0.png)
[snd2.psb.decompressed.resx.json.zip](https://github.com/UlyssesWu/FreeMote/files/8858856/snd2.psb.decompressed.resx.json.zip)

**Comment by UlyssesWu** [comment]
I think now I need the json file, and the `FreeMote.Psb.dll` from `FreeMoteToolkit\lib` folder

**Comment by N-Games** [comment]
Here you go:
[Stuff.zip](https://github.com/UlyssesWu/FreeMote/files/8860372/Stuff.zip)

**Comment by UlyssesWu** [comment]
oh... if you check `snd2.psb.decompressed.json` and compare with other jsons, you will understand there is no audio in this file. It's just a kind of "index" for other audio archive PSBs. 

>  I'm able to extract snd2.psb.decompressed.psb, but I can extract menu1.psb.decompressed.psb for some reason.

Your words confused me, I thought `menu1.psb` is the problematic one.

**Comment by N-Games** [comment]
Oh ok. The part about snd2 makes sense, but I can't decrypt menu1.psb for some reason. I'm able to extract your file (menu1.psb.decompressed.psb) but when I tried to decrypt the original file (menu1.psb.m) it didn't work. So I can't decrypt it, but I can extract it for some reason. All the other files worked fine btw

**Comment by UlyssesWu** [comment]
>  I tried to decrypt the original file (menu1.psb.m) it didn't work

I need to see the output to diagnose.

**Comment by N-Games** [comment]
Oh never mind, it works now. I think I misspelled it. Thank you so much for your help!
