### ISSUE TITLE
Unhandled Exception when running FreeMote on OneDrive

### ISSUE THREAD

**Issue by MarquesCoding** [UlyssesWu/FreeMote#84]
* Read [wiki](https://github.com/UlyssesWu/FreeMote/wiki)
* Provide game name and platform (PC/Android/PSP etc.)
* Provide PSB file samples
* Program output, or screenshots

Having issue when trying to run psbdecompile.exe on my windows 11 pc.

![image](https://user-images.githubusercontent.com/40672230/173249639-8928dc81-66fa-4df1-9c2e-b79e6a6abccf.png)

**Comment by UlyssesWu** [comment]
Do not run it on OneDrive, or make `FreeMoteTootkit` "always keep on this device" (in context menu).

**Comment by UlyssesWu** [comment]
Close due to no response.
