### ISSUE TITLE
[Question] 匿名代码(Anonymous;Code)中BC7格式图像的支持

### ISSUE THREAD

**Issue by wetor** [UlyssesWu/FreeMote#85]
游戏名：匿名代码(Anonymous;Code)  
平台：Nintendo Switch  
样本：[ac_lifegame.psb.m.zip](https://github.com/UlyssesWu/FreeMote/files/9026754/ac_lifegame.psb.m.zip)  
问题描述：此游戏中的图像使用了暂不支持的dds BC7格式。
附一个支持BC7的直播录播：https://www.twitch.tv/videos/1516600820

请问会考虑支持此格式吗？

**Comment by UlyssesWu** [comment]
twitch网络问题，看不了。
会考虑支持的，不过目前感觉没有特别优雅的方案（尽量不native，尽量不升framework版本，尽量同时支持decode/encode），待有空再决定用什么。

目前你可以暂时用`-raw`参数自己处理图片格式。

**Comment by UlyssesWu** [comment]
RGBA8 (LE):
![image](https://user-images.githubusercontent.com/4312781/177049599-0d87797e-f88b-41ec-aeac-f79fa489d974.png)

RGBA8 (BE):
![image](https://user-images.githubusercontent.com/4312781/177049671-9f669473-d1e6-4648-8871-5b404cc4f63f.png)


我不知道哪种颜色是对的，看样子应该是BE的？

**Comment by wetor** [comment]
> RGBA8 (LE): ![image](https://user-images.githubusercontent.com/4312781/177049599-0d87797e-f88b-41ec-aeac-f79fa489d974.png)
> 
> RGBA8 (BE): ![image](https://user-images.githubusercontent.com/4312781/177049671-9f669473-d1e6-4648-8871-5b404cc4f63f.png)
> 
> 我不知道哪种颜色是对的，看样子应该是BE的？

没错，是下面的BE

**Comment by UlyssesWu** [comment]
支持是支持了，但是这个encode效率efficiency……仍然很低，对于你这个样本，需要40多秒才能从PNG转成BC7。
而使用三方工具Compressonator的话，encode不到10秒。不过这个工具本身比较大，还不是绿色版（要安装），不太优雅。
感觉这个BCn编码库还有较大的优化空间，但是没精力去研究，后面有空时再试下C++库好了。

**Comment by ruje0504** [comment]
进来学习，嘿嘿

**Comment by UlyssesWu** [comment]
Related post: https://kuriko.moe/#/Projects/%E6%B1%89%E5%8C%96/Anonymous;Code/%E6%80%BB%E7%BB%93/
