### ISSUE TITLE
[PsbDecompile]Fail to convert scn files to json files 

### ISSUE THREAD

**Issue by Francis-Komizu** [UlyssesWu/FreeMote#88]
I have some scn files of Sonoba Witch and I want to convert them to json files. But each time I drag them to `PsbDecompile.exe`, the program craches within a few seconds and there's no results. I have VS2022 and NET4.8 on my computer and I've also checked `FreeMote.Plugins.dll` and `FreeMote.Plugins.x64.dll`, founding they are not blocked at all. 

Here's the file sample and screenshot. I feel grateful if you cound help me!

![1](https://user-images.githubusercontent.com/87693204/180943462-74d4b12b-53eb-474f-9cc1-cea8f5c1bc7a.png)

![2](https://user-images.githubusercontent.com/87693204/180943488-a2230376-4422-4be2-b613-ab008fae3eb4.png)

[test.ks.zip](https://github.com/UlyssesWu/FreeMote/files/9187307/test.ks.zip)

**Comment by UlyssesWu** [comment]
显然这是一个加密过的PSB，你需要分析游戏搞清楚它是怎么加密的。
如果你把前半段XOR 0x40，随后XOR 0xA0，你就能看到一个稍微正常一点的PSB，但此时格式还不是完全对，具体哪里还要XOR，不分析游戏逻辑只能一点点尝试，暂时没这个时间。

**Comment by Francis-Komizu** [comment]
> 

好的，谢谢解答！

**Comment by UlyssesWu** [comment]
如果你正确地进行了上述两个xor操作（如果没搞懂，下面有xor后的文件），最新的CI build版本将可以输出json文件，当然，这个文件的内容是不完整的，忽略了所有的错误，所以重新生成PSB是没用的，只能用来看下文本。我能做到的大概也就这些了。要完整解只能你自己去分析游戏的加载。

目前尚不清楚这个奇怪的格式是因为还有地方没有正确解密，还是因为英化（？）使用的工具不完善导致。
[test.ks.zip](https://github.com/UlyssesWu/FreeMote/files/9188908/test.ks.zip)

**Comment by Francis-Komizu** [comment]
好的，我研究研究:)

这个ks.scn是一些visual novels的字幕文件。我一朋友直接使用psbDecompile成功转成了json，里面的文本也是完整的。或许是我电脑环境的问题吧。总之谢谢大佬！
