### ISSUE TITLE
FreeMoteViewer无法打开psb,报错

### ISSUE THREAD

**Issue by rewjx** [UlyssesWu/FreeMote#89]
pc平台的游戏 ガマンができない童貞兄キと、スナオになれない反抗妹，
提取得到的psb文件可以用psbDecompile得到多张png图片和json文件，但是在使用FreemoteViewer时报错。
报错如下：

![捕获](https://user-images.githubusercontent.com/40747772/183231479-43e29ccf-6ca0-45d5-b091-1919036239b9.PNG)

附上一个样本：

[eva01.zip](https://github.com/UlyssesWu/FreeMote/files/9274295/eva01.zip)

**Comment by UlyssesWu** [comment]
已经修过了，用最新测试版（CI Build）
https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts

**Comment by UlyssesWu** [comment]
顺便问下你提取这个游戏所用的工具

**Comment by rewjx** [comment]
> 顺便问下你提取这个游戏所用的工具

谢谢大佬。
可以用krkrzextract或krkrdump: https://github.com/crskycode/KrkrDump 都可以。但是是dump方式，只能玩到哪游戏引擎读取了才能获取到。

**Comment by UlyssesWu** [comment]
好的，看来目前确实没有解新Cx（Hxv4）更好的方式。
