### ISSUE TITLE
[Question]兄啊，我自己打包回去的字体，重新用PsbDecompile解出来之后图片没画面呀

### ISSUE THREAD

**Issue by YiJunYanHe** [UlyssesWu/FreeMote#90]
* Read [wiki](https://github.com/UlyssesWu/FreeMote/wiki)
* Provide game name and platform (PC/Android/PSP etc.)
* Provide PSB file samples
* Program output, or screenshots
[原资源包解压.zip](https://github.com/UlyssesWu/FreeMote/files/9477149/default.zip)
[打包用.zip](https://github.com/UlyssesWu/FreeMote/files/9477157/default.zip)
[重新解压后.zip](https://github.com/UlyssesWu/FreeMote/files/9477160/default.zip)

是不是我的图还没做到那个规格。。。因为游戏字体原图打包回去再解压是没问题的

**Comment by UlyssesWu** [comment]
没有提供**原始PSB**，不好定位问题。甚至“[原资源包解压.zip](https://github.com/UlyssesWu/FreeMote/files/9477149/default.zip)”也没有上传成功。

**Comment by YiJunYanHe** [comment]
> 没有提供**原始PSB**，不好定位问题。甚至“[原资源包解压.zip](https://github.com/UlyssesWu/FreeMote/files/9477149/default.zip)”也没有上传成功。

不好意思，昨天发烧躺医院了，我直接把那个body.bin还有psb.m还有key发给你吧。
[font_body.zip](https://github.com/UlyssesWu/FreeMote/files/9484099/font_body.zip)

key：a23e898ef1032  l：131

我打算是打包回42字号的那个。

**Comment by UlyssesWu** [comment]
初步推断是你的图片尺寸不是2^n（2048,4096,8192等等），对于此平台要求的格式（CI4_SW/CI8_SW）的texture，尺寸非2^n是不合法的，不能正确SW（Swizzle）。
我暂时没有验证，但你身体无碍后若有空可以先试试。

**Comment by YiJunYanHe** [comment]
> 初步推断是你的图片尺寸不是2^n（2048,4096,8192等等），对于此平台要求的格式（CI4_SW/CI8_SW）的texture，尺寸非2^n是不合法的，不能正确SW（Swizzle）。 我暂时没有验证，但你身体无碍后若有空可以先试试。

感谢老兄，再解压正常了

![image](https://user-images.githubusercontent.com/58536722/188843092-38292011-7166-41aa-9b2a-6842c518cbb0.png)

**Comment by YiJunYanHe** [comment]
我可以关问题了吗？

**Comment by UlyssesWu** [comment]
只要你没问题了就可以。
不过从追求极致的角度，建议把尺寸调整的合理一些，尽量不要有太多空白面积，否则游戏的性能会受影响（占更多内存）。
你可以看到原游戏为此是分成两张图的，就是因为一张图的话会有很多空白。
后续当FreeMote发现边长非2^n时，会增加一些提示。

**Comment by YiJunYanHe** [comment]
实际再看看吧，，，我用Bitmap Font Generator做的图，一直很头疼fnt文件里面的参数怎么对应上去原映射表的。

**Comment by Rimi-kun** [comment]
ср, 7 сент. 2022 г., 12:55 YiJunYanHe ***@***.***>:
