### ISSUE TITLE
Error on Opening PSBdecompile

### ISSUE THREAD

**Issue by QBASpriteFinder** [UlyssesWu/FreeMote#91]
When ever I tried to open the PSBdecompile in the Freemote toolkit It closes itself out with an error no matter how many times I click on it. Can you help me out? I'm trying to use it to get character sprites in the (Images.Bin file) from new game the challenge stage from it, And I have no Idea why it keeps closing itself out on me like this...

**Comment by UlyssesWu** [comment]
![fm-1](https://user-images.githubusercontent.com/4312781/193439501-a53b1095-d974-424c-b5ac-bef2184b2928.png)

And read wiki first:
* https://github.com/UlyssesWu/FreeMote/wiki#guide-for-rookies
* https://github.com/UlyssesWu/FreeMote/wiki/CommandLine-Usage-for-Tools#info-psb

**Comment by UlyssesWu** [comment]
Close due to no response.
