### ISSUE TITLE
Invalid data when decoding

### ISSUE THREAD

**Issue by QBASpriteFinder** [UlyssesWu/FreeMote#92]
I had unblocked the plugins just like you said. (And sorry I was slow in response and didn't answer my original post in time.) How ever I keep getting this when I put the psb-decomplier and the new game challenge stage image file in the cmd prompt... How do I extract the image files?
![Screenshot (202)](https://user-images.githubusercontent.com/73131161/195866238-5ec7f9d6-8a9c-4c5d-a688-aaec6fe1a0dd.png)

**Comment by QBASpriteFinder** [comment]
This time I used the (image_info.psb.m) and the key 1232ab23478cd. But I still get the same result somehow... Can you show me how to do this step by step? I'm a real beginner at this...
![Screenshot (204)](https://user-images.githubusercontent.com/73131161/197402286-a8c38319-830c-4cd4-ad8c-cc7cf0e7f9b8.png)

**Comment by UlyssesWu** [comment]
**YOU SHOULD READ WIKI CAREFULLY FIRST**

`PsbDecompile info-psb -k 1232ab23478cd -l 131 -a image_info.psb.m`

**Comment by QBASpriteFinder** [comment]
I read the wiki this time (https://github.com/UlyssesWu/FreeMote/wiki/CommandLine-Usage-for-Tools#info-psb) 
![Screenshot (206)](https://user-images.githubusercontent.com/73131161/198170019-9652b326-32bc-437a-9651-89f818318843.png)
and tried the command you provided me with, (PsbDecompile info-psb -k 1232ab23478cd -l 131 -a image_info.psb.m) but now I get this message... Sorry but can you please help me...

**Comment by UlyssesWu** [comment]
Check your path. If you want to run a program, your cmd path should be located in its folder. I see your correct path in your first 2 screenshots, but not the last one.

P.S. This should be the last reply for questions not related to FreeMote itself. If you have googled something like `is not recognized as an internal or external command`, you can already figure it out by yourself. 

http://www.catb.org/~esr/faqs/smart-questions.html

**Comment by QBASpriteFinder** [comment]
Did I do it right? Cause I think I did.
![Screenshot (207)](https://user-images.githubusercontent.com/73131161/199146019-dea400e4-6dff-4f4f-bb35-bb84b21f1e9a.png)

**Comment by UlyssesWu** [comment]
"PsbDecompile" is duplicated.

In Command Prompt, `PsbDecompile.exe` is equal to `PsbDecompile`. You shouldn't write it twice. It should be:
`C:\Users\QooAppBoy\Videos\Ulysses-FreeMoteToolkit-v3.3.0\FreeMoteToolkit\PsbDecompile.exe info-psb -k 1232ab23478cd -l 131 -a image_info.psb.m` (you can replace `PsbDecompile.exe` to `PsbDecompile`)

Execute this and a folder will be created and the content of image_body.bin will be in it. However, sometimes you may only find some other `.psb.m` or `.psb` files in it, which means they are also packed (like zip files in a zip file). You can use this command to extract all files:

`C:\Users\QooAppBoy\Videos\Ulysses-FreeMoteToolkit-v3.3.0\FreeMoteToolkit\PsbDecompile.exe info-psb -k 1232ab23478cd -l 131 -a image_info.psb.m -a`

**Comment by QBASpriteFinder** [comment]
I used the line (C:\Users\QooAppBoy\Videos\Ulysses-FreeMoteToolkit-v3.3.0\FreeMoteToolkit\PsbDecompile.exe info-psb -k 1232ab23478cd -l 131 -a image_info.psb.m -a) But I still get this...
![Screenshot (209)](https://user-images.githubusercontent.com/73131161/199151429-be3878db-288d-4ed3-b012-9f64fb882994.png)

**Comment by UlyssesWu** [comment]
> Execute this and **a folder will be created** and the content of image_body.bin will be in it.

Check `C:\Users\QooAppBoy\Videos\Ulysses-FreeMoteToolkit-v3.3.0\FreeMoteToolkit\`

**Comment by QBASpriteFinder** [comment]
I did exactly what you said both (C:\Users\QooAppBoy\Videos\Ulysses-FreeMoteToolkit-v3.3.0\FreeMoteToolkit\PsbDecompile.exe info-psb -k 1232ab23478cd -l 131 -a image_info.psb.m -a) AND (C:\Users\QooAppBoy\Videos\Ulysses-FreeMoteToolkit-v3.3.0\FreeMoteToolkit\PsbDecompile info-psb -k 1232ab23478cd -l 131 -a image_info.psb.m -a) 

But I Still get this message and no folder appears...

![Screenshot (212)](https://user-images.githubusercontent.com/73131161/199153946-b243342f-0ec3-411f-9c84-1ab7f6903152.png)

**Comment by UlyssesWu** [comment]
Upload files to let me check.

**Comment by QBASpriteFinder** [comment]
Here's the (image_info.psb.m) file, I can't upload the (image_body.bin) file it's over (786,824) kb

[image_body.zip](https://github.com/UlyssesWu/FreeMote/files/9906772/image_body.zip)

**Comment by UlyssesWu** [comment]
There is nothing wrong with `image_info.psb.m` . The command should work if the `image_body.bin` is also correct. 
It cannot be so fast (less than 1 sec) if all things are correct. So there might be something wrong with `image_body.bin`.
I can't help you more without that file. Good luck.

**Comment by QBASpriteFinder** [comment]
Here's both the (image_info.psb.m) file AND the (image_body.bin) (Divided into 2 parts with the help of QuickBms) from the New game challenge stage. You can try and do the extraction on your end and see if you get the same results as me. And if that doesn't work here is a link to New game the Challenge stage game where I go the files so that you can try it out on your end as well. (https://drive.google.com/file/d/12TiPbdPE1j4wWm7gB01LDb9DaTmarS26/view?pli=1) 


[image_info.psb.zip](https://github.com/UlyssesWu/FreeMote/files/9942901/image_info.psb.zip)
[image_body.zip](https://github.com/UlyssesWu/FreeMote/files/9942906/image_body.zip)

**Comment by UlyssesWu** [comment]
The image_body.zip is almost useless because it's just 2 random slices from original image_body.bin file. It's neither a start nor an end of one packed file. You need to upload a full `image_body.bin`, or slice the file according to the decompiled `image_info.psb.m.json`'s `file_info`. 
And, I will not download the whole game just to verify if my tool works. If you cannot upload the correct files (I think you can upload it using GoogleDrive), you can just try other tools. You're not the first one to extract "New Game", as you can see there are already some issues about it here (#27). There must be some tool (maybe not mine) since they can dump the game correctly.
I think there could be something wrong with your extraction of image_body.bin itself. There could be some extra bytes at the beginning of the bin file, or, the file might be encrypted.

**Comment by QBASpriteFinder** [comment]
No luck... But thanks for trying to help me. I'll start a new thread If I have future problems with this extraction.
