### ISSUE TITLE
[Question]关于key的问题

### ISSUE THREAD

**Issue by qingchunnh** [UlyssesWu/FreeMote#93]
游戏是switch平台的五等分の花嫁∬ ～夏の思い出も五等分～
看到你说要去非PSB文件里找key，但是这个游戏全部都是PSB文件，这种情况下该如何找到key
![1](https://user-images.githubusercontent.com/96961592/200997228-46c1c58c-ea01-4cb8-9b5e-778f0a4f0e39.png)

**Comment by UlyssesWu** [comment]
你要去**二进制文件**（即包含程序逻辑的文件，比如PC游戏就是dll或者exe）里找key，解密的逻辑显然位于这种文件中。
这个游戏相关的issue我已经回答了不下10个了，很多人已经在问题里说过key是什么。你感兴趣可以自己翻一翻之前的issue。

**Comment by qingchunnh** [comment]
> 你要去**二进制文件**（即包含程序逻辑的文件，比如PC游戏就是dll或者exe）里找key，解密的逻辑显然位于这种文件中。 这个游戏相关的issue我已经回答了不下10个了，很多人已经在问题里说过key是什么。你感兴趣可以自己翻一翻之前的issue。

除了我图片里的文件就只剩下mp4格式的文件了，其他的全部都是PSB文件，找不到其他的文件了，所以他一定会有一个存放key的二进制文件吗，但是这个游戏全部都是PSB文件

**Comment by qingchunnh** [comment]
我在switch的文件里找到了key，感谢作者

**Comment by ruje0504** [comment]
exefs里面
