### ISSUE TITLE
[Audio] WAV plugin conflict

### ISSUE THREAD

**Issue by LIBRA847** [UlyssesWu/FreeMote#94]
您好，我使用您的FreeMote尝试拆解M2在APM3街机框体上发行的Senjin Aleste（战刃雅士达）有关音频的psb文件，但反编译出来的文件夹内没有任何文件，但此psb文件是几个psb文件中大小最大的
![bgm](https://user-images.githubusercontent.com/119226181/204149974-d7ba975a-f15f-48f9-a2fa-f8233112bf98.PNG)
![bgm1](https://user-images.githubusercontent.com/119226181/204150064-6d53b64d-5229-4211-83bb-1efe42ec2df9.PNG)
但json里包含有关其内部音频文件的信息，如何拆解出音频文件？
![bgm1 json](https://user-images.githubusercontent.com/119226181/204150177-2b555d6e-1e12-4453-b7a9-1f3f7e15cdae.PNG)
原文件由于太大无法直接上传，链接：https://1drv.ms/u/s!AikaY3ZrdkD8hGZzYBb-IfClD6Q_?e=BuUaFF

**Comment by LIBRA847** [comment]
此外，bgm02和bgm03虽然都能反编译出文件，格式均为xwma，但出现的文件总数无法对上对应生成json内所包含的曲目名数量

**Comment by UlyssesWu** [comment]
是bug。请等待修复。

**Comment by UlyssesWu** [comment]
尝试最新测试版：https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts

XWMA需要外部工具才能转换成WAV，详情阅读wiki：https://github.com/UlyssesWu/FreeMote/wiki/Audio#xwma-windows

bgm01中的WAV是ADPCM WAV而非常见的PCM WAV，不能用win10/11自带的音乐app打开。如需要转换成PCM WAV，可用`ffmpeg -i bgm01.wav.wav bgm01-pcm.wav`。

voice中的音频文件小而多，解包需要1分钟以上。

**Comment by LIBRA847** [comment]
> 尝试最新测试版：https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts
> 
> XWMA需要外部工具才能转换成WAV，详情阅读wiki：https://github.com/UlyssesWu/FreeMote/wiki/Audio#xwma-windows
> 
> bgm01中的WAV是ADPCM WAV而非常见的PCM WAV，不能用win10/11自带的音乐app打开（可用foobar2000、Windows Media Player等）。如需要转换成PCM WAV，可用`ffmpeg -i bgm01.wav.wav bgm01-pcm.wav`。
> 
> voice中的音频文件小而多，解包需要1分钟以上。

已成功提取文件，非常感谢帮助！
