### ISSUE TITLE
[Question] [ご注文はうさぎですか wonderful party] Blue filter on images

### ISSUE THREAD

**Issue by MrShiruba** [UlyssesWu/FreeMote#95]
Game affected : ご注文はうさぎですか wonderful party
Platform : PS Vita, 2016

I was interested in the voice clips from the game but out of curiosity I attempted to extract the images / graphics of the game. I came across  [https://github.com/UlyssesWu/FreeMote/issues/40](this). So I looked for the key which was in the eboot.bin of the game and is : a23e898ef1032.
On the command prompt I then did `PsbDecompile.exe info-psb -k a23e898ef1032 image_info.psb.m -l 131 -a` and suceeded in extracting the file. The problem is there is some weird blue filter on the images. Upon extracting the voices (`PsbDecompile.exe info-psb -k a23e898ef1032 voice_info.psb.m -l 131 -a`) I got normal .wav audio so I don't know if the problem is the command or the file. Below is a comparison :

Left is how she normally looks and right is how the extracted files look like :
![image](https://user-images.githubusercontent.com/111703557/206025828-ea416fdc-098c-4141-b484-2a451426cebb.png)  ![cocoa_blue](https://user-images.githubusercontent.com/111703557/206026582-afe7cab4-c7bc-4c7b-8b9e-339fdca151b8.png)

Download link for image_body.bin and image_info.psb.m : [here](https://drive.google.com/file/d/1p_gSG3voXAY-EzAIcGEIlR9_DgrLNh4e/view?usp=share_link)

**Comment by UlyssesWu** [comment]
Try latest CI build: https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts

**Comment by MrShiruba** [comment]
Thanks!
If anyone is interested the command is still the same : `PsbDecompile.exe info-psb -k a23e898ef1032 <file.psb.m> -l 131 -a`

**Comment by MrShiruba** [comment]
Sorry to reopen this issue.
Upon checking the other files of the game, I noticed that not every image are in the "image_info.psb.m" and are also in other files, for example "motion_info.psb.m". 
Download link for the other psb.m [here](https://drive.google.com/file/d/116YdHHqaWvNk3WXMIUp7LdTIcgYHXFtg/view?usp=share_link).

Upon extracting this file (`PsbDecompile.exe info-psb -k a23e898ef1032 motion_info.psb.m -l 131 -a`), there is a missing file in the directory `shop.psb.m`, namely the number 7 in brown shade. The thing is "6" is named `tex#018-texture.png` and "8" `tex#020-texture.png` so the program is conscious that `tex#019-texture.png` is missing.

![gochiusa_7_missing](https://user-images.githubusercontent.com/111703557/208982587-07c70691-c52c-49a4-9867-ad00250335fc.png)

Is it fixable? If not don't worry I don't mind.

**Comment by guranu** [comment]
> Game affected : ご注文はうさぎですか wonderful party Platform : PS Vita, 2016
> 
> I was interested in the voice clips from the game but out of curiosity I attempted to extract the images / graphics of the game. I came across [https://github.com/UlyssesWu/FreeMote/issues/40](this). So I looked for the key which was in the eboot.bin of the game and is : a23e898ef1032. On the command prompt I then did `PsbDecompile.exe info-psb -k a23e898ef1032 image_info.psb.m -l 131 -a` and suceeded in extracting the file. The problem is there is some weird blue filter on the images. Upon extracting the voices (`PsbDecompile.exe info-psb -k a23e898ef1032 voice_info.psb.m -l 131 -a`) I got normal .wav audio so I don't know if the problem is the command or the file. Below is a comparison :
> 
> Left is how she normally looks and right is how the extracted files look like : ![image](https://user-images.githubusercontent.com/111703557/206025828-ea416fdc-098c-4141-b484-2a451426cebb.png) ![cocoa_blue](https://user-images.githubusercontent.com/111703557/206026582-afe7cab4-c7bc-4c7b-8b9e-339fdca151b8.png)
> 
> Download link for image_body.bin and image_info.psb.m : [here](https://drive.google.com/file/d/1p_gSG3voXAY-EzAIcGEIlR9_DgrLNh4e/view?usp=share_link)

@MrShiruba how did you found the mdf key?

**Comment by MrShiruba** [comment]
@guranu Look here : https://zenhax.com/viewtopic.php?t=7898
It's in eboot.bin just before "script/.script_info.psb.m". Open eboot.bin with an hex editor.
