### ISSUE TITLE
[PSV] [ご注文はうさぎですか wonderful party] different Pal + same resource = missing texture when output

### ISSUE THREAD

**Issue by MrShiruba** [UlyssesWu/FreeMote#98]
Sorry to open another issue for the same game. Upon checking the other files, I noticed that not every image is in the "image_info.psb.m" and are also in other files, for example "motion_info.psb.m". 
Download link for the other psb.m [here](https://drive.google.com/file/d/116YdHHqaWvNk3WXMIUp7LdTIcgYHXFtg/view?usp=share_link).

Upon extracting this file (`PsbDecompile.exe info-psb -k a23e898ef1032 motion_info.psb.m -l 131 -a`), there is a missing file in the directory `shop.psb.m`, namely the number 7 in brown shade. The thing is "6" is named `tex#018-texture.png` and "8" `tex#020-texture.png` so the program is conscious that `tex#019-texture.png` is missing.

![gochiusa_7_missing](https://user-images.githubusercontent.com/111703557/208982587-07c70691-c52c-49a4-9867-ad00250335fc.png)

Is it fixable? If not don't worry I don't mind.

**Comment by UlyssesWu** [comment]
Try latest CI build: [ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts](https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts)

**Comment by MrShiruba** [comment]
Sorry for the inconvenience and thanks again!
