### ISSUE TITLE
[Question] Fail to extract combined images from *.dpak files by doing `PsbDecompile.exe image "*.dpak"`

### ISSUE THREAD

**Issue by h1531095** [UlyssesWu/FreeMote#99]
I used your `*.dpak` sample [[PNG]Dsd001__tsxjkv.dpak](/Dual-Vector-Foil/FreeMote.Samples/blob/main/dpak/%5BPNG%5Dsd001__tsxjkv.dpak) for the test. By executing:
```cmd
PsbDecompile.exe image "[PNG]sd001__tsxjkv.dpak"
```
I got the error message below.
```cmd
FreeMote PSB Decompiler
by Ulysses, wdwxy12345@gmail.com
2 Plugins Loaded.

System.ArgumentException: ?????
   ? System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   ? FreeMote.RL.ConvertToImage(Byte[] data, Int32 width, Int32 height, PsbPixelFormat colorFormat) ? X:\FreeMote\FreeMote\RL.cs: ? 38
   ? FreeMote.RL.ConvertToImage(Byte[] data, Byte[] palette, Int32 width, Int32 height, PsbPixelFormat colorFormat, PsbPixelFormat paletteColorFormat) ? X:\FreeMote\FreeMote\RL.cs: ? 24
   ? FreeMote.Psb.PsbResHelper.UnlinkImages(PSB psb, PsbLinkOrderBy order, Boolean disposeResInPsb) ? X:\FreeMote\FreeMote.Psb\PsbResHelper.cs: ? 341
   ? FreeMote.PsBuild.PsbDecompiler.ExtractImageFiles(String inputPath, PsbImageFormat format) ? X:\FreeMote\FreeMote.PsBuild\PsbDecompiler.cs: ? 344
   ? FreeMote.Tools.PsbDecompile.Program.<>c__DisplayClass0_1.<Main>b__4() ? X:\FreeMote\FreeMote.Tools.PsbDecompile\Program.cs: ? 92
Done.
```
On the other hand, there is no problem in extracting files by simply doing:
```cmd
PsbDecompile.exe "[PNG]sd001__tsxjkv.dpak"
```
However, my goal is to get properly overlayed combined images from the `*.dpak` file.
Is `PsbDecompile.exe image` not the right function to use? Or is it a bug?

By the way, I also tried to understand the logic behind overlaying images in PSB archives by tweaking codes such as FreeMote and GARbro, but got no luck so far.
From my understanding, in FreeMote, image offset information recorded in `*.dpak` files are stored as [ImageMetadata.Top] and [ImageMetadata.Left] and called to combine images of different sizes. Can you give some hints on how to read out these variables?

Thank you for your time.

PS I made a related post for GARbro too: morkt/GARbro/issues/573. As it seems you know GARbro quite well too, I figure putting this as a reference might help you to understand the problem that I have better.

[ImageMetadata.Top]: /UlyssesWu/FreeMote/blob/master/FreeMote.Psb/PsbResHelper.cs#L808
[ImageMetadata.Left]: /UlyssesWu/FreeMote/blob/master/FreeMote.Psb/PsbResHelper.cs#L809

**Comment by UlyssesWu** [comment]
`image` command is designed for `image` (or `Tachie`, `imageList`) type PSB, not for dpak. 
For `image` type PSB, see PSBs in `image` folder of FreeMote.Samples. And here is a screenshot: https://github.com/UlyssesWu/FreeMote/issues/40#issuecomment-624598750

You already know there is nothing about the layer position in dpak itself, so as a PSB processing lib, FreeMote can not do more thing for you. I will just stop it from throwing errors.

**Comment by h1531095** [comment]
Thank you very much for the answer.
Do you by chance know where the layer position information are?
I was falsely certain that those must inside the dpak files because I noticed that GARbro can open `*.dref` files and overlay images properly.
Given that a `*.dref` file is nothing but a text file with lines pointing to `*.dpak` entries, e.g.,
```
psb://cg001_01__rjjkqx.dpak/cg001_01r2.tlg
psb://cg001_01__rjjkqx.dpak/5113e17476c12cb0bf377f8e34704566.png
```
, I could only assume that those
 information must be stored in `*.dpak` side by side with other image metadata such as image width and height...
But it seems not to be the case.

I am even more confused now. How do GARbro make it work then... I would like to do some more research about this, maybe starting from checking what are stored in `*.dpak` files  exactly. Not sure how though. Is there an easy way to read out `*.dpak` header and metadata of each entry?

**Comment by UlyssesWu** [comment]
The `.json` file produced by PsbDecompile already contains all information in a PSB (dpak). So there is no need to check dpak for such info. You should debug GARbro (set BP at `BlendLayer` maybe) for details. I don't have full dpak samples (with dref files, and maybe other metadata files are also required) so good luck.

**Comment by h1531095** [comment]
Yes, that's what I was thinking too...

I already tested some full samples which is already confimed to be convertable by GARbro, and I could find no thing but filenames in the json files produced from PsbDecompile.

Also, thanks for the suggestion and I will check the function that you mentioned later.
